const map = {    "UsageTestAssignment": () => Promise.resolve({"_TypeModel":{"name":"UsageTestAssignment","since":1,"type":"AGGREGATED_TYPE","id":59,"rootId":"BXVzYWdlADs","versioned":false,"encrypted":false,"values":{"_id":{"id":60,"type":"CustomId","cardinality":"One","final":true,"encrypted":false},"name":{"id":62,"type":"String","cardinality":"One","final":false,"encrypted":false},"sendPings":{"id":64,"type":"Boolean","cardinality":"One","final":false,"encrypted":false},"testId":{"id":61,"type":"GeneratedId","cardinality":"One","final":true,"encrypted":false},"variant":{"id":63,"type":"Number","cardinality":"ZeroOrOne","final":true,"encrypted":false}},"associations":{"stages":{"id":65,"type":"AGGREGATION","cardinality":"Any","final":false,"refType":"UsageTestStage","dependency":null}},"app":"usage","version":"1"}}),
    "UsageTestAssignmentIn": () => Promise.resolve({"_TypeModel":{"name":"UsageTestAssignmentIn","since":1,"type":"DATA_TRANSFER_TYPE","id":56,"rootId":"BXVzYWdlADg","versioned":false,"encrypted":false,"values":{"_format":{"id":57,"type":"Number","cardinality":"One","final":false,"encrypted":false},"testDeviceId":{"id":58,"type":"GeneratedId","cardinality":"ZeroOrOne","final":false,"encrypted":false}},"associations":{},"app":"usage","version":"1"}}),
    "UsageTestAssignmentOut": () => Promise.resolve({"_TypeModel":{"name":"UsageTestAssignmentOut","since":1,"type":"DATA_TRANSFER_TYPE","id":66,"rootId":"BXVzYWdlAEI","versioned":false,"encrypted":false,"values":{"_format":{"id":67,"type":"Number","cardinality":"One","final":false,"encrypted":false},"testDeviceId":{"id":68,"type":"GeneratedId","cardinality":"One","final":false,"encrypted":false}},"associations":{"assignments":{"id":69,"type":"AGGREGATION","cardinality":"Any","final":false,"refType":"UsageTestAssignment","dependency":null}},"app":"usage","version":"1"}}),
    "UsageTestMetricConfig": () => Promise.resolve({"_TypeModel":{"name":"UsageTestMetricConfig","since":1,"type":"AGGREGATED_TYPE","id":15,"rootId":"BXVzYWdlAA8","versioned":false,"encrypted":false,"values":{"_id":{"id":16,"type":"CustomId","cardinality":"One","final":true,"encrypted":false},"name":{"id":17,"type":"String","cardinality":"One","final":true,"encrypted":false},"type":{"id":18,"type":"Number","cardinality":"One","final":true,"encrypted":false}},"associations":{"configValues":{"id":19,"type":"AGGREGATION","cardinality":"Any","final":false,"refType":"UsageTestMetricConfigValue","dependency":null}},"app":"usage","version":"1"}}),
    "UsageTestMetricConfigValue": () => Promise.resolve({"_TypeModel":{"name":"UsageTestMetricConfigValue","since":1,"type":"AGGREGATED_TYPE","id":11,"rootId":"BXVzYWdlAAs","versioned":false,"encrypted":false,"values":{"_id":{"id":12,"type":"CustomId","cardinality":"One","final":true,"encrypted":false},"key":{"id":13,"type":"String","cardinality":"One","final":false,"encrypted":false},"value":{"id":14,"type":"String","cardinality":"One","final":false,"encrypted":false}},"associations":{},"app":"usage","version":"1"}}),
    "UsageTestMetricData": () => Promise.resolve({"_TypeModel":{"name":"UsageTestMetricData","since":1,"type":"AGGREGATED_TYPE","id":20,"rootId":"BXVzYWdlABQ","versioned":false,"encrypted":false,"values":{"_id":{"id":21,"type":"CustomId","cardinality":"One","final":true,"encrypted":false},"name":{"id":22,"type":"String","cardinality":"One","final":true,"encrypted":false},"value":{"id":23,"type":"String","cardinality":"One","final":true,"encrypted":false}},"associations":{},"app":"usage","version":"1"}}),
    "UsageTestParticipationIn": () => Promise.resolve({"_TypeModel":{"name":"UsageTestParticipationIn","since":1,"type":"DATA_TRANSFER_TYPE","id":83,"rootId":"BXVzYWdlAFM","versioned":false,"encrypted":false,"values":{"_format":{"id":84,"type":"Number","cardinality":"One","final":false,"encrypted":false},"stage":{"id":86,"type":"Number","cardinality":"One","final":false,"encrypted":false},"testDeviceId":{"id":87,"type":"GeneratedId","cardinality":"One","final":false,"encrypted":false},"testId":{"id":85,"type":"GeneratedId","cardinality":"One","final":false,"encrypted":false}},"associations":{"metrics":{"id":88,"type":"AGGREGATION","cardinality":"Any","final":false,"refType":"UsageTestMetricData","dependency":null}},"app":"usage","version":"1"}}),
    "UsageTestStage": () => Promise.resolve({"_TypeModel":{"name":"UsageTestStage","since":1,"type":"AGGREGATED_TYPE","id":38,"rootId":"BXVzYWdlACY","versioned":false,"encrypted":false,"values":{"_id":{"id":39,"type":"CustomId","cardinality":"One","final":true,"encrypted":false},"name":{"id":40,"type":"String","cardinality":"One","final":false,"encrypted":false}},"associations":{"metrics":{"id":41,"type":"AGGREGATION","cardinality":"Any","final":false,"refType":"UsageTestMetricConfig","dependency":null}},"app":"usage","version":"1"}}),
}
export default map