// Generated from the IANA Time Zone Database v2026b.
// See script generate-time-zones.js in admin-client helpers.
export const availableIANATimeZones = [
	"Africa/Abidjan",
	"Africa/Accra",
	"Africa/Addis_Ababa",
	"Africa/Algiers",
	"Africa/Asmera",
	"Africa/Bamako",
	"Africa/Bangui",
	"Africa/Banjul",
	"Africa/Bissau",
	"Africa/Blantyre",
	"Africa/Brazzaville",
	"Africa/Bujumbura",
	"Africa/Cairo",
	"Africa/Casablanca",
	"Africa/Ceuta",
	"Africa/Conakry",
	"Africa/Dakar",
	"Africa/Dar_es_Salaam",
	"Africa/Djibouti",
	"Africa/Douala",
	"Africa/El_Aaiun",
	"Africa/Freetown",
	"Africa/Gaborone",
	"Africa/Harare",
	"Africa/Johannesburg",
	"Africa/Juba",
	"Africa/Kampala",
	"Africa/Khartoum",
	"Africa/Kigali",
	"Africa/Kinshasa",
	"Africa/Lagos",
	"Africa/Libreville",
	"Africa/Lome",
	"Africa/Luanda",
	"Africa/Lubumbashi",
	"Africa/Lusaka",
	"Africa/Malabo",
	"Africa/Maputo",
	"Africa/Maseru",
	"Africa/Mbabane",
	"Africa/Mogadishu",
	"Africa/Monrovia",
	"Africa/Nairobi",
	"Africa/Ndjamena",
	"Africa/Niamey",
	"Africa/Nouakchott",
	"Africa/Ouagadougou",
	"Africa/Porto-Novo",
	"Africa/Sao_Tome",
	"Africa/Tripoli",
	"Africa/Tunis",
	"Africa/Windhoek",
	"America/Adak",
	"America/Anchorage",
	"America/Anguilla",
	"America/Antigua",
	"America/Araguaina",
	"America/Argentina/La_Rioja",
	"America/Argentina/Rio_Gallegos",
	"America/Argentina/Salta",
	"America/Argentina/San_Juan",
	"America/Argentina/San_Luis",
	"America/Argentina/Tucuman",
	"America/Argentina/Ushuaia",
	"America/Aruba",
	"America/Asuncion",
	"America/Bahia",
	"America/Bahia_Banderas",
	"America/Barbados",
	"America/Belem",
	"America/Belize",
	"America/Blanc-Sablon",
	"America/Boa_Vista",
	"America/Bogota",
	"America/Boise",
	"America/Buenos_Aires",
	"America/Cambridge_Bay",
	"America/Campo_Grande",
	"America/Cancun",
	"America/Caracas",
	"America/Catamarca",
	"America/Cayenne",
	"America/Cayman",
	"America/Chicago",
	"America/Chihuahua",
	"America/Ciudad_Juarez",
	"America/Coral_Harbour",
	"America/Cordoba",
	"America/Costa_Rica",
	"America/Coyhaique",
	"America/Creston",
	"America/Cuiaba",
	"America/Curacao",
	"America/Danmarkshavn",
	"America/Dawson",
	"America/Dawson_Creek",
	"America/Denver",
	"America/Detroit",
	"America/Dominica",
	"America/Edmonton",
	"America/Eirunepe",
	"America/El_Salvador",
	"America/Fort_Nelson",
	"America/Fortaleza",
	"America/Glace_Bay",
	"America/Godthab",
	"America/Goose_Bay",
	"America/Grand_Turk",
	"America/Grenada",
	"America/Guadeloupe",
	"America/Guatemala",
	"America/Guayaquil",
	"America/Guyana",
	"America/Halifax",
	"America/Havana",
	"America/Hermosillo",
	"America/Indiana/Knox",
	"America/Indiana/Marengo",
	"America/Indiana/Petersburg",
	"America/Indiana/Tell_City",
	"America/Indiana/Vevay",
	"America/Indiana/Vincennes",
	"America/Indiana/Winamac",
	"America/Indianapolis",
	"America/Inuvik",
	"America/Iqaluit",
	"America/Jamaica",
	"America/Jujuy",
	"America/Juneau",
	"America/Kentucky/Monticello",
	"America/Kralendijk",
	"America/La_Paz",
	"America/Lima",
	"America/Los_Angeles",
	"America/Louisville",
	"America/Lower_Princes",
	"America/Maceio",
	"America/Managua",
	"America/Manaus",
	"America/Marigot",
	"America/Martinique",
	"America/Matamoros",
	"America/Mazatlan",
	"America/Mendoza",
	"America/Menominee",
	"America/Merida",
	"America/Metlakatla",
	"America/Mexico_City",
	"America/Miquelon",
	"America/Moncton",
	"America/Monterrey",
	"America/Montevideo",
	"America/Montserrat",
	"America/Nassau",
	"America/New_York",
	"America/Nome",
	"America/Noronha",
	"America/North_Dakota/Beulah",
	"America/North_Dakota/Center",
	"America/North_Dakota/New_Salem",
	"America/Ojinaga",
	"America/Panama",
	"America/Paramaribo",
	"America/Phoenix",
	"America/Port-au-Prince",
	"America/Port_of_Spain",
	"America/Porto_Velho",
	"America/Puerto_Rico",
	"America/Punta_Arenas",
	"America/Rankin_Inlet",
	"America/Recife",
	"America/Regina",
	"America/Resolute",
	"America/Rio_Branco",
	"America/Santarem",
	"America/Santiago",
	"America/Santo_Domingo",
	"America/Sao_Paulo",
	"America/Scoresbysund",
	"America/Sitka",
	"America/St_Barthelemy",
	"America/St_Johns",
	"America/St_Kitts",
	"America/St_Lucia",
	"America/St_Thomas",
	"America/St_Vincent",
	"America/Swift_Current",
	"America/Tegucigalpa",
	"America/Thule",
	"America/Tijuana",
	"America/Toronto",
	"America/Tortola",
	"America/Vancouver",
	"America/Whitehorse",
	"America/Winnipeg",
	"America/Yakutat",
	"Antarctica/Casey",
	"Antarctica/Davis",
	"Antarctica/DumontDUrville",
	"Antarctica/Macquarie",
	"Antarctica/Mawson",
	"Antarctica/McMurdo",
	"Antarctica/Palmer",
	"Antarctica/Rothera",
	"Antarctica/Troll",
	"Antarctica/Vostok",
	"Arctic/Longyearbyen",
	"Asia/Anadyr",
	"Asia/Barnaul",
	"Asia/Chita",
	"Asia/Irkutsk",
	"Asia/Kamchatka",
	"Asia/Khandyga",
	"Asia/Krasnoyarsk",
	"Asia/Magadan",
	"Asia/Novokuznetsk",
	"Asia/Novosibirsk",
	"Asia/Omsk",
	"Asia/Sakhalin",
	"Asia/Srednekolymsk",
	"Asia/Tomsk",
	"Asia/Ust-Nera",
	"Asia/Vladivostok",
	"Asia/Yakutsk",
	"Asia/Yekaterinburg",
	"Atlantic/Azores",
	"Atlantic/Bermuda",
	"Atlantic/Canary",
	"Atlantic/Cape_Verde",
	"Atlantic/Faeroe",
	"Atlantic/Madeira",
	"Atlantic/Reykjavik",
	"Atlantic/South_Georgia",
	"Atlantic/St_Helena",
	"Atlantic/Stanley",
	"Australia/Adelaide",
	"Australia/Brisbane",
	"Australia/Broken_Hill",
	"Australia/Darwin",
	"Australia/Eucla",
	"Australia/Hobart",
	"Australia/Lindeman",
	"Australia/Lord_Howe",
	"Australia/Melbourne",
	"Australia/Perth",
	"Australia/Sydney",
	"Europe/Amsterdam",
	"Europe/Andorra",
	"Europe/Astrakhan",
	"Europe/Athens",
	"Europe/Belgrade",
	"Europe/Berlin",
	"Europe/Bratislava",
	"Europe/Brussels",
	"Europe/Bucharest",
	"Europe/Budapest",
	"Europe/Busingen",
	"Europe/Chisinau",
	"Europe/Copenhagen",
	"Europe/Dublin",
	"Europe/Gibraltar",
	"Europe/Guernsey",
	"Europe/Helsinki",
	"Europe/Isle_of_Man",
	"Europe/Istanbul",
	"Europe/Jersey",
	"Europe/Kaliningrad",
	"Europe/Kiev",
	"Europe/Kirov",
	"Europe/Lisbon",
	"Europe/Ljubljana",
	"Europe/London",
	"Europe/Luxembourg",
	"Europe/Madrid",
	"Europe/Malta",
	"Europe/Mariehamn",
	"Europe/Minsk",
	"Europe/Monaco",
	"Europe/Moscow",
	"Europe/Oslo",
	"Europe/Paris",
	"Europe/Podgorica",
	"Europe/Prague",
	"Europe/Riga",
	"Europe/Rome",
	"Europe/Samara",
	"Europe/San_Marino",
	"Europe/Sarajevo",
	"Europe/Saratov",
	"Europe/Simferopol",
	"Europe/Skopje",
	"Europe/Sofia",
	"Europe/Stockholm",
	"Europe/Tallinn",
	"Europe/Tirane",
	"Europe/Ulyanovsk",
	"Europe/Vaduz",
	"Europe/Vatican",
	"Europe/Vienna",
	"Europe/Vilnius",
	"Europe/Volgograd",
	"Europe/Warsaw",
	"Europe/Zagreb",
	"Europe/Zurich",
	"Indian/Antananarivo",
	"Indian/Comoro",
	"Indian/Mauritius",
	"Indian/Mayotte",
	"Pacific/Apia",
	"Pacific/Auckland",
	"Pacific/Bougainville",
	"Pacific/Chatham",
	"Pacific/Easter",
	"Pacific/Efate",
	"Pacific/Enderbury",
	"Pacific/Fakaofo",
	"Pacific/Fiji",
	"Pacific/Funafuti",
	"Pacific/Galapagos",
	"Pacific/Gambier",
	"Pacific/Guadalcanal",
	"Pacific/Guam",
	"Pacific/Honolulu",
	"Pacific/Kiritimati",
	"Pacific/Kosrae",
	"Pacific/Kwajalein",
	"Pacific/Majuro",
	"Pacific/Marquesas",
	"Pacific/Midway",
	"Pacific/Nauru",
	"Pacific/Niue",
	"Pacific/Norfolk",
	"Pacific/Noumea",
	"Pacific/Pago_Pago",
	"Pacific/Palau",
	"Pacific/Pitcairn",
	"Pacific/Ponape",
	"Pacific/Port_Moresby",
	"Pacific/Rarotonga",
	"Pacific/Saipan",
	"Pacific/Tahiti",
	"Pacific/Tarawa",
	"Pacific/Tongatapu",
	"Pacific/Truk",
	"Pacific/Wake",
	"Pacific/Wallis",
]
// Autogenerated file with mapping from Windows zones to IANA zones
// See Unicode CLDR project
export const windowsToIANATimeZones: Record<string, string> = {
	"Afghanistan Standard Time": "Asia/Kabul",
	"Alaskan Standard Time": "America/Anchorage",
	"Aleutian Standard Time": "America/Adak",
	"Altai Standard Time": "Asia/Barnaul",
	"Arab Standard Time": "Asia/Riyadh",
	"Arabian Standard Time": "Asia/Dubai",
	"Arabic Standard Time": "Asia/Baghdad",
	"Argentina Standard Time": "America/Buenos_Aires",
	"Astrakhan Standard Time": "Europe/Astrakhan",
	"Atlantic Standard Time": "America/Halifax",
	"AUS Central Standard Time": "Australia/Darwin",
	"Aus Central W. Standard Time": "Australia/Eucla",
	"AUS Eastern Standard Time": "Australia/Sydney",
	"Azerbaijan Standard Time": "Asia/Baku",
	"Azores Standard Time": "Atlantic/Azores",
	"Bahia Standard Time": "America/Bahia",
	"Bangladesh Standard Time": "Asia/Dhaka",
	"Belarus Standard Time": "Europe/Minsk",
	"Bougainville Standard Time": "Pacific/Bougainville",
	"Canada Central Standard Time": "America/Regina",
	"Cape Verde Standard Time": "Atlantic/Cape_Verde",
	"Caucasus Standard Time": "Asia/Yerevan",
	"Cen. Australia Standard Time": "Australia/Adelaide",
	"Central America Standard Time": "America/Guatemala",
	"Central Asia Standard Time": "Asia/Almaty",
	"Central Brazilian Standard Time": "America/Cuiaba",
	"Central Europe Standard Time": "Europe/Budapest",
	"Central European Standard Time": "Europe/Warsaw",
	"Central Pacific Standard Time": "Pacific/Guadalcanal",
	"Central Standard Time": "America/Chicago",
	"Central Standard Time (Mexico)": "America/Mexico_City",
	"Chatham Islands Standard Time": "Pacific/Chatham",
	"China Standard Time": "Asia/Shanghai",
	"Cuba Standard Time": "America/Havana",
	"Dateline Standard Time": "Etc/GMT+12",
	"E. Africa Standard Time": "Africa/Nairobi",
	"E. Australia Standard Time": "Australia/Brisbane",
	"E. Europe Standard Time": "Europe/Chisinau",
	"E. South America Standard Time": "America/Sao_Paulo",
	"Easter Island Standard Time": "Pacific/Easter",
	"Eastern Standard Time": "America/New_York",
	"Eastern Standard Time (Mexico)": "America/Cancun",
	"Egypt Standard Time": "Africa/Cairo",
	"Ekaterinburg Standard Time": "Asia/Yekaterinburg",
	"Fiji Standard Time": "Pacific/Fiji",
	"FLE Standard Time": "Europe/Kiev",
	"Georgian Standard Time": "Asia/Tbilisi",
	"GMT Standard Time": "Europe/London",
	"Greenland Standard Time": "America/Godthab",
	"Greenwich Standard Time": "Atlantic/Reykjavik",
	"GTB Standard Time": "Europe/Bucharest",
	"Haiti Standard Time": "America/Port-au-Prince",
	"Hawaiian Standard Time": "Pacific/Honolulu",
	"India Standard Time": "Asia/Calcutta",
	"Iran Standard Time": "Asia/Tehran",
	"Israel Standard Time": "Asia/Jerusalem",
	"Jordan Standard Time": "Asia/Amman",
	"Kaliningrad Standard Time": "Europe/Kaliningrad",
	"Korea Standard Time": "Asia/Seoul",
	"Libya Standard Time": "Africa/Tripoli",
	"Line Islands Standard Time": "Pacific/Kiritimati",
	"Lord Howe Standard Time": "Australia/Lord_Howe",
	"Magadan Standard Time": "Asia/Magadan",
	"Magallanes Standard Time": "America/Punta_Arenas",
	"Marquesas Standard Time": "Pacific/Marquesas",
	"Mauritius Standard Time": "Indian/Mauritius",
	"Middle East Standard Time": "Asia/Beirut",
	"Montevideo Standard Time": "America/Montevideo",
	"Morocco Standard Time": "Africa/Casablanca",
	"Mountain Standard Time": "America/Denver",
	"Mountain Standard Time (Mexico)": "America/Chihuahua",
	"Myanmar Standard Time": "Asia/Rangoon",
	"N. Central Asia Standard Time": "Asia/Novosibirsk",
	"Namibia Standard Time": "Africa/Windhoek",
	"Nepal Standard Time": "Asia/Katmandu",
	"New Zealand Standard Time": "Pacific/Auckland",
	"Newfoundland Standard Time": "America/St_Johns",
	"Norfolk Standard Time": "Pacific/Norfolk",
	"North Asia East Standard Time": "Asia/Irkutsk",
	"North Asia Standard Time": "Asia/Krasnoyarsk",
	"North Korea Standard Time": "Asia/Pyongyang",
	"Omsk Standard Time": "Asia/Omsk",
	"Pacific SA Standard Time": "America/Santiago",
	"Pacific Standard Time": "America/Los_Angeles",
	"Pacific Standard Time (Mexico)": "America/Tijuana",
	"Pakistan Standard Time": "Asia/Karachi",
	"Paraguay Standard Time": "America/Asuncion",
	"Romance Standard Time": "Europe/Paris",
	"Russia Time Zone 3": "Europe/Samara",
	"Russia Time Zone 10": "Asia/Srednekolymsk",
	"Russia Time Zone 11": "Asia/Kamchatka",
	"Russian Standard Time": "Europe/Moscow",
	"SA Eastern Standard Time": "America/Cayenne",
	"SA Pacific Standard Time": "America/Bogota",
	"SA Western Standard Time": "America/La_Paz",
	"Saint Pierre Standard Time": "America/Miquelon",
	"Sakhalin Standard Time": "Asia/Sakhalin",
	"Samoa Standard Time": "Pacific/Apia",
	"Sao Tome Standard Time": "Africa/Sao_Tome",
	"Saratov Standard Time": "Europe/Saratov",
	"SE Asia Standard Time": "Asia/Bangkok",
	"Singapore Standard Time": "Asia/Singapore",
	"South Africa Standard Time": "Africa/Johannesburg",
	"Sri Lanka Standard Time": "Asia/Colombo",
	"Sudan Standard Time": "Africa/Khartoum",
	"Syria Standard Time": "Asia/Damascus",
	"Taipei Standard Time": "Asia/Taipei",
	"Tasmania Standard Time": "Australia/Hobart",
	"Tocantins Standard Time": "America/Araguaina",
	"Tokyo Standard Time": "Asia/Tokyo",
	"Tomsk Standard Time": "Asia/Tomsk",
	"Tonga Standard Time": "Pacific/Tongatapu",
	"Transbaikal Standard Time": "Asia/Chita",
	"Turkey Standard Time": "Europe/Istanbul",
	"Turks And Caicos Standard Time": "America/Grand_Turk",
	"Ulaanbaatar Standard Time": "Asia/Ulaanbaatar",
	"US Eastern Standard Time": "America/Indianapolis",
	"US Mountain Standard Time": "America/Phoenix",
	UTC: "Etc/GMT",
	"UTC-02": "Etc/GMT+2",
	"UTC-08": "Etc/GMT+8",
	"UTC-09": "Etc/GMT+9",
	"UTC-11": "Etc/GMT+11",
	"UTC+12": "Etc/GMT-12",
	"UTC+13": "Etc/GMT-13",
	"Venezuela Standard Time": "America/Caracas",
	"Vladivostok Standard Time": "Asia/Vladivostok",
	"W. Australia Standard Time": "Australia/Perth",
	"W. Central Africa Standard Time": "Africa/Lagos",
	"W. Europe Standard Time": "Europe/Berlin",
	"W. Mongolia Standard Time": "Asia/Hovd",
	"West Asia Standard Time": "Asia/Tashkent",
	"West Bank Standard Time": "Asia/Hebron",
	"West Pacific Standard Time": "Pacific/Port_Moresby",
	"Yakutsk Standard Time": "Asia/Yakutsk",
}
