/*
Copyright (C) 2023 Signal Messenger, LLC.
SPDX-License-Identifier: AGPL-3.0-only
*/


#ifndef SIGNAL_FTS5_TOKENIZER_H_
#define SIGNAL_FTS5_TOKENIZER_H_

/* This file was automatically generated by cbindgen */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#define SIGNAL_FTS5_TOKENIZER_EXTENSION_H_

typedef struct Fts5Tokenizer Fts5Tokenizer;

#if defined(SIGNAL_FTS5_TOKENIZER_EXTENSION_H_)
typedef struct sqlite3 sqlite3;
#endif

#if defined(SIGNAL_FTS5_TOKENIZER_EXTENSION_H_)
typedef struct Sqlite3Stmt Sqlite3Stmt;
#endif

/**
 * Wrapper for FFI
 * Obtained from signal_tokenize(), must be freed by calling signal_tokenize_free()
 */
typedef struct Tokenized Tokenized;

typedef int (*sqlite3__fts5_token_fn)(void *p_ctx,
                                      int t_flags,
                                      const char *p_token,
                                      int n_token,
                                      int i_start,
                                      int i_end);

#if defined(SIGNAL_FTS5_TOKENIZER_EXTENSION_H_)
typedef void *(*Sqlite3Malloc64)(uint64_t);
#endif

#if defined(SIGNAL_FTS5_TOKENIZER_EXTENSION_H_)
typedef int (*Sqlite3Prepare)(struct sqlite3 *db,
                              const char *query,
                              int query_len,
                              struct Sqlite3Stmt **stmt,
                              const char **pz_tail);
#endif

#if defined(SIGNAL_FTS5_TOKENIZER_EXTENSION_H_)
typedef int (*Sqlite3BindPointer)(struct Sqlite3Stmt *stmt,
                                  int index,
                                  void *ptr,
                                  const char *name,
                                  void (*cb)(void*));
#endif

#if defined(SIGNAL_FTS5_TOKENIZER_EXTENSION_H_)
typedef int (*Sqlite3Finalize)(struct Sqlite3Stmt *stmt);
#endif

#if defined(SIGNAL_FTS5_TOKENIZER_EXTENSION_H_)
typedef int (*Sqlite3Step)(struct Sqlite3Stmt *stmt);
#endif

#if defined(SIGNAL_FTS5_TOKENIZER_EXTENSION_H_)
typedef int (*Sqlite3LibversionNumber)(void);
#endif

#if defined(SIGNAL_FTS5_TOKENIZER_EXTENSION_H_)
/**
 * sqlite3 routines that are actually used by the tokenizer extension
 */
typedef struct UsefulSqlite3ApiRoutines {
  Sqlite3Malloc64 malloc64;
  Sqlite3Prepare prepare;
  Sqlite3BindPointer bind_pointer;
  Sqlite3Finalize finalize;
  Sqlite3Step step;
  Sqlite3LibversionNumber libversion_number;
} UsefulSqlite3ApiRoutines;
#endif

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct Tokenized *signal_tokenize(const char *query);

char *const *signal_tokenize_from_ptr(struct Tokenized *tokenized);

void signal_tokenize_free(struct Tokenized *tokenized);

int signal_fts5_tokenize(struct Fts5Tokenizer *_tokenizer,
                         void *p_ctx,
                         int _flags,
                         const char *p_text,
                         int n_text,
                         sqlite3__fts5_token_fn x_token);

#if defined(SIGNAL_FTS5_TOKENIZER_EXTENSION_H_)
/**
 * Init sqlite3 without needing to access the whole sqlite3_api_routines vtable.
 * Blessed (literally) way to write extensions is to use SQLITE_EXTENSION_INIT family of macros
 * which uses vtable variable in scope instead of whatever is passed into the entry point.
 * We are doing this to be able to statically link against the extension but to still be able to
 * compile extension without needing to compile C first.
 */
int signal_fts5_tokenizer_init_static(struct sqlite3 *db,
                                      char **pz_err_msg,
                                      const struct UsefulSqlite3ApiRoutines *api);
#endif

#if defined(SIGNAL_FTS5_TOKENIZER_EXTENSION_H_)
int signal_fts5_tokenizer_init(struct sqlite3 *db, char **pz_err_msg, const void *p_api);
#endif

#if defined(SIGNAL_FTS5_TOKENIZER_EXTENSION_H_)
int fts5_create_signal_tokenizer(void *_p_context,
                                 const unsigned char *const *_az_arg,
                                 int _n_arg,
                                 struct Fts5Tokenizer **fts5_tokenizer);
#endif

#if defined(SIGNAL_FTS5_TOKENIZER_EXTENSION_H_)
void fts5_delete_signal_tokenizer(struct Fts5Tokenizer *fts5_tokenizer);
#endif

#if defined(SIGNAL_FTS5_TOKENIZER_EXTENSION_H_)
void fts5_destroy_icu_module(void *_module);
#endif

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SIGNAL_FTS5_TOKENIZER_H_ */
