/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * current state of the imap import for this tuta account
 * requires an initialized SDK!
 */
export const enum ImapImportStatus {
	NotInitialized = 0,
	Paused = 1,
	Running = 2,
	Postponed = 3,
	Finished = 4,
}
export interface ImapImportConfig {
	rootImportMailFolderName: string
	credentials: ImapCredentials
	importTargetAddress: string
}
/** passed in from js before being validated and used for logging into the imap server */
export interface ImapCredentials {
	/** hostname of the imap server to import mail from */
	host: string
	/** imap port of the imap server to import mail from */
	port: number
	username?: string
	password?: string
	accessToken?: string
}
/** Passed in from js-side, will be validated before being converted to proper tuta sdk credentials. */
export interface TutaCredentials {
	apiUrl: string
	clientVersion: string
	login: string
	userId: string
	accessToken: string
	encryptedPassphraseKey: Array<number>
	credentialType: TutaCredentialType
}
export const enum TutaCredentialType {
	Internal = "Internal",
	External = "External",
}
export declare class ImapImport {
	status: ImapImportStatus
	importConfig: ImapImportConfig
	static initialize(imapImportConfig: ImapImportConfig): ImapImport
	continueImportNapi(): Promise<void>
	deleteImport(): Promise<ImapImportStatus>
	pauseImport(): Promise<ImapImportStatus>
}
export declare class ImportCredentials {
	static setup(tutaCredentials: TutaCredentials, imapCredentials: ImapCredentials): ImportCredentials
	/** Log into tuta + imap and return a handle to an object that can be used to control the import process. */
	login(): Promise<Importer>
}
export declare class Importer {}
