/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * current state of the imap_reader import for this tuta account
 * requires an initialized SDK!
 */
export const enum ImportState {
	NotInitialized = 0,
	Paused = 1,
	Running = 2,
	Postponed = 3,
	Finished = 4,
}
export interface ImportStatus {
	state: ImportState
	importedMails: number
}
/** Passed in from js-side, will be validated before being converted to proper tuta sdk credentials. */
export interface TutaCredentials {
	apiUrl: string
	clientVersion: string
	login: string
	userId: string
	accessToken: string
	encryptedPassphraseKey: Array<number>
	credentialType: TutaCredentialType
}
export const enum TutaCredentialType {
	Internal = 0,
	External = 1,
}
/** Wrapper for `Importer` to be used from napi-rs interface */
export declare class ImporterApi {
	continueImport(): Promise<ImportStatus>
	deleteImport(): Promise<ImportStatus>
	pauseImport(): Promise<ImportStatus>
	static createFileImporter(
		tutaCredentials: TutaCredentials,
		targetOwnerGroup: string,
		targetMailFolder: [string, string],
		sourcePaths: Array<string>,
	): Promise<ImporterApi>
}
