/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** passed in from js before being validated and used for logging into the imap_reader server */
export interface ImapCredentials {
  /** hostname of the imap_reader server to import mail from */
  host: string
  /** imap_reader port of the imap_reader server to import mail from */
  port: number
  /** Login method */
  loginMechanism: LoginMechanism
}
| { type2: 'Plain', username: string, password: string }
| { type2: 'OAuth', accessToken: string }
export interface ImapImportConfig {
  rootImportMailFolderName: string
  credentials: ImapCredentials
}
| { type2: 'Imap', imapImportConfig: ImapImportConfig }
| { type2: 'LocalFile', filePath: string, isMbox: boolean }
/**
 * current state of the imap_reader import for this tuta account
 * requires an initialized SDK!
 */
export const enum ImportStatus {
  NotInitialized = 0,
  Paused = 1,
  Running = 2,
  Postponed = 3,
  Finished = 4
}
/** Passed in from js-side, will be validated before being converted to proper tuta sdk credentials. */
export interface TutaCredentials {
  apiUrl: string
  clientVersion: string
  login: string
  userId: string
  accessToken: string
  encryptedPassphraseKey: Array<number>
  credentialType: TutaCredentialType
}
Internal = 'Internal',
External = 'External'
export declare class ImportBuilder {
  static setup(tutaCredentials: TutaCredentials, importSourceAuth: ImportAuth, targetMailAddress: string): ImportBuilder
  build(): Promise<Importer>
}
export declare class FileImport { }
export declare class ImapImport { }
export declare class ImapImportState { }
export declare class Importer {
  continueImportNapi(): Promise<void>
  deleteImport(): Promise<ImportStatus>
  pauseImport(): Promise<ImportStatus>
}
