import { createEcmaScriptPlugin, type GeneratedFile, type Schema, runNodeJs, getComments, Printable } from "@bufbuild/protoplugin"
import { type DescFile, type DescMethod, getOption } from "@bufbuild/protobuf"
import { registerEvent } from "../gen/proto/v1/customOptions_pb"

// Generates an Interface from .proto file
// Supports empty method arguments
// Supports void for method return
// Supports streaming for method arguments and return https://github.com/cloudflare/capnweb#pass-by-value-types

const plugin = createEcmaScriptPlugin({
	name: "protoc-gen-capnweb",
	version: "v1",
	generateTs(schema: Schema) {
		for (const file of schema.files) {
			if (file.services.length === 0) continue

			const f = schema.generateFile(`${file.name}_capnweb.ts`)
			f.preamble(file)
			f.print(`// Generate Interfaces to be used by <a href="https://github.com/cloudflare/capnweb">Cap'n Web</a> for RPC.`)

			generateServices(file, f)
		}
	},
})

function generateServices(file: DescFile, f: GeneratedFile) {
	for (const service of file.services) {
		f.print()
		f.print(f.export("interface", service.name), " {")

		for (const method of service.methods) {
			printComments(f, method)
			printMethod(f, method)

			// const value = getOption(method, registerEvent)
		}

		f.print("}")
	}
}

function printComments(f: GeneratedFile, method: DescMethod) {
	const comment = getComments(method).leading

	if (comment) {
		f.print(`/** ${comment} */`)
	}
}

function printMethod(f: GeneratedFile, method: DescMethod) {
	// Input TS shapes (method parameter and return types generated by buf.build/bufbuild/es)
	const inputShape = f.importShape(method.input)
	const outputShape = f.importShape(method.output)

	// check if function arguments are empty or return value is void
	const noFuncArgs = method.input.fields.length === 0
	const noFuncRet = method.output.fields.length === 0
	// check if argument is streamed
	const retStreamed = method.methodKind === "server_streaming"
	const argsStreamed = method.methodKind === "client_streaming"

	const methodName = method.name.charAt(0).toLowerCase() + method.name.slice(1)

	const noArgs: Printable[] = ["()"]
	const normalArgs: Printable[] = ["(request: ", inputShape, ")"]
	const streamArgs: Printable[] = ["(request: WritableStream<", inputShape, ">)"]
	const methodArgs: Printable[] = noFuncArgs ? noArgs : argsStreamed ? streamArgs : normalArgs

	const voidReturn: Printable[] = [": Promise<void>;"]
	const normalReturn: Printable[] = [": Promise<", outputShape, ">;"]
	const streamReturn: Printable[] = [": Promise<ReadableStream<", outputShape, ">>;"]
	const methodReturn: Printable[] = noFuncRet ? voidReturn : retStreamed ? streamReturn : normalReturn

	f.print("    ", methodName, methodArgs, methodReturn)
}

runNodeJs(plugin)
