export const FontIcons = Object.freeze({
	Reply: `\uea01`,
	ReplyAll: `\uea02`,
	Warning: `\uea03`,
	Forward: `\uea04`,
	Attach: `\uea05`,
	Folder: `\uea06`,
	Inbox: `\uea07`,
	Sent: `\uea08`,
	Trash: `\uea09`,
	Archive: `\uea0a`,
	Spam: `\uea0b`,
	Draft: `\uea0c`,
	Edit: `\uea0d`,
	Confidential: `\uea0e`,
	PQConfidential: `\uea0f`,
	Checkbox: `\uea10`,
} as const)
