export default {
	universal: {
		companyName: "Tutao GmbH",
		addressStreet: "Deisterstr. 17a",
		tutaFax: "Fax: +49 511202801-19",
		tutaEmail: "sales@tutao.de",
		tutaWebsite: "https://tuta.com",
	},
	en: {
		addressPostal: "30449 Hanover",
		addressCountry: "Germany",
		addressCity: "Hanover",
		tutaPhone: "Phone: +49 511202801-0",
		yourCustomerId: "Your customer ID:",

		invoiceNumber: "Invoice number",
		invoice: "Invoice",
		credit: "Credit",
		cancelCredit: "Credit cancellation",
		asAgreedBlock: "As agreed we kindly request the following payment:",

		quantity: "Quantity",
		item: "Item",
		singlePrice: "Single price",
		totalPrice: "Total price",
		subTotal: "Sub total",
		grandTotal: "Grand total",
		addedVat: "+",
		includedVat: "incl.",
		vatPercent: "% VAT",

		reverseChargeVatIdNumber1: "All prices are net prices. The recipient is liable for VAT under the reverse charge mechanism",
		reverseChargeVatIdNumber2: "(German: Steuerschuld des Leistungsempfängers).",
		yourVatId: "Your VAT identification number:",
		netPricesNoVatInGermany: "All prices are net prices and not subject to value added tax in Germany.",
		noVatInGermany: "Prices are not subject to value added tax in Germany.",

		paymentInvoiceDue1: "The payment is due 7 days after the invoice date without any deduction. Please",
		paymentInvoiceDue2: "transfer the grand total with reference to the invoice number to our account:",
		paymentInvoiceHolder: "Account holder: Tutao GmbH",
		paymentInvoiceBank: "Bank: Commerzbank Hannover",
		paymentInvoiceIBAN: "IBAN: DE67 2508 0020 0138 0400 01",
		paymentInvoiceBIC: "BIC: DRESDEFF250",
		paymentInvoiceProvideNumber1: "Please name only the invoice number",
		paymentInvoiceProvideNumber2: "in the payment as reference.",
		paymentInvoiceBankSwitched:
			"Please note that we have recently switched to a different bank. Please make certain that you transfer your payment to our new account. Thanks!",

		paymentCreditCard: "The grand total will be debited from your credit card.",
		paymentPaypal: "The grand total will be debited from your PayPal account.",
		paymentAccountBalance: "The grand total was debited from your account balance.",
		thankYou: "Thank you very much!",

		legalNoSigned: "This document was created automatically and is not signed.",
		legalRepresented: "Tutanota® is a service of Tutao GmbH, represented by: Arne Möhle, Matthias Pfau;Company domiciled in:",
		legalRegistration: "Hannover, Germany; Register court: Court of first instance Hannover, Register number: HRB 208014",
		legalVatIdentification: "VAT identification number: DE280903265; Creditor Identifier: DE48TTT00001013919",
		legalBankAccount: "Bank account: Commerzbank Hannover, IBAN: DE67 2508 0020 0138 0400 01, BIC: DRESDEFF250",

		premiumUser: "Tutanota Premium user accounts",
		starterUser: "Tutanota for Outlook user accounts",
		starterUserPackage: "Account package Tutanota for Outlook",
		starterUserPackageUpgrade: "Account package upgrade Tutanota for Outlook",
		storagePackage: "Storage",
		storagePackageUpgrade: "Storage upgrade",
		emailAliasPackage: "Email aliases",
		emailAliasPackageUpgrade: "Upgrade email aliases",
		sharedMailGroup: "Shared mailboxes",
		whitelabelFeature: "Whitelabel feature per user",
		contactFormUnused: "Contact forms",
		whitelabelChild: "Whitelabel accounts",
		localAdminGroup: "Local admin group",
		discount: "Discount",
		sharingFeature: "Sharing feature per user",
		creditType: "Credit for Tutanota usage fees",
		giftCard: "Tutanota gift card",
		businessFeature: "Business feature per user",
		giftCardMigration: "Gift card correction",
		referralCredit: "Credit for referred user",
		cancelledReferralCredit: "Cancelled credit for referred user",
		revolutionaryAccount: "Revolutionary accounts",
		legendAccount: "Legend Accounts",
		essentialAccount: "Essential Accounts",
		advancedAccount: "Advanced Accounts",
		unlimitedAccount: "Unlimited Accounts",
	},
	de: {
		addressPostal: "30449 Hannover",
		addressCountry: "Deutschland",
		addressCity: "Hannover",
		tutaPhone: "Fon: +49 511202801-0",
		yourCustomerId: "Ihre Kundennummer:",

		invoiceNumber: "Rechnungsnummer",
		invoice: "Rechnung",
		credit: "Gutschrift",
		cancelCredit: "Stornierung Gutschrift",
		asAgreedBlock: "Vereinbarungsgemäß rechnen wir folgende Leistungen ab:",

		reverseChargeVatIdNumber1: "Alle Beträge sind netto. Die Steuerschuldnerschaft geht auf Sie als Leistungsempfänger über.",
		reverseChargeVatIdNumber2: "",
		yourVatId: "Ihre Umsatzsteuer-Identifikationsnummer:",
		netPricesNoVatInGermany: "Alle Beträge sind netto und werden nicht in Deutschland versteuert.",
		noVatInGermany: "Beträge werden nicht in Deutschland versteuert.",

		quantity: "Menge",
		item: "Item",
		singlePrice: "Einzelpreis",
		totalPrice: "Gesamtpreis",
		subTotal: "Betrag",
		grandTotal: "Gesamtbetrag",
		addedVat: "zzgl.",
		includedVat: "inkl.",
		vatPercent: "% Umsatzsteuer",

		paymentInvoiceDue1: "Der Rechnungsbetrag ist sieben Tage nach Rechnungsdatum ohne Abzug fällig. Bitte",
		paymentInvoiceDue2: "überweisen Sie den Rechnungsbetrag unter Angabe der Rechnungsnummer auf unser Konto:",
		paymentInvoiceHolder: "Inhaber: Tutao GmbH",
		paymentInvoiceBank: "Bank: Commerzbank Hannover",
		paymentInvoiceIBAN: "IBAN: DE67 2508 0020 0138 0400 01",
		paymentInvoiceBIC: "",
		paymentInvoiceProvideNumber1: "Bitte geben Sie bei der Zahlung nur die Rechnungsnummer",
		paymentInvoiceProvideNumber2: "als Referenz an.",
		paymentInvoiceBankSwitched:
			"Achtung: Unsere Bankverbindung hat sich geändert. Bitte stellen Sie sicher, dass Sie den Rechnungsbetrag auf unser neues Konto überweisen. Danke!",

		paymentCreditCard: "Der Rechnungsbetrag wird von Ihrer Kreditkarte eingezogen.",
		paymentPaypal: "Der Rechnungsbetrag wird von Ihrem PayPal-Account abgebucht.",
		paymentAccountBalance: "Der Rechnungsbetrag wurde von dem Guthaben ihres Kontos abgezogen.",
		thankYou: "Vielen Dank!",

		legalNoSigned: "Dieses Schreiben wurde maschinell erstellt und enthält keine Unterschrift.",
		legalRepresented: "Tutanota® ist ein Service der Tutao GmbH, vertreten durch: Arne Möhle, Matthias Pfau",
		legalRegistration: "Sitz der Gesellschaft: Hannover, Registergericht: Amtsgericht Hannover, Registernummer: HRB 208014",
		legalVatIdentification: "Umsatzsteuer-Identifikationsnummer (USt-IdNr.): DE280903265, Gläubiger-Identifikationsnummer:",
		legalBankAccount: "DE48TTT00001013919, Bankverbindung: Commerzbank Hannover, IBAN: DE67 2508 0020 0138 0400 01",

		premiumUser: "Tutanota Premium Benutzer-Accounts",
		starterUser: "Tutanota für Outlook Benutzer-Accounts",
		starterUserPackage: "Account-Paket Tutanota für Outlook",
		starterUserPackageUpgrade: "Erweiterung Account-Paket Tutanota für Outlook",
		storagePackage: "Speicherkapazität",
		storagePackageUpgrade: "Erweiterung Speicherkapazität",
		emailAliasPackage: "E-Mail-Aliasse",
		emailAliasPackageUpgrade: "Erweiterung E-Mail-Aliasse",
		sharedMailGroup: "Geteilte Mailboxen",
		whitelabelFeature: "Whitelabel-Funktion pro Benutzer",
		contactFormUnused: "Kontaktformulare",
		whitelabelChild: "Whitelabel-Accounts",
		localAdminGroup: "Lokale Admin-Gruppe",
		discount: "Rabatt",
		sharingFeature: "Teilen-Funktion pro Benutzer",
		creditType: "Gutschrift für Tutanota Nutzungsgebühren",
		giftCard: "Tutanota Gutschein",
		businessFeature: "Business-Funktion pro Benutzer",
		giftCardMigration: "Korrektur Gutschein",
		referralCredit: "Gutschrift für geworbenen Benutzer",
		cancelledReferralCredit: "Stornierung Gutschrift für geworbenen Benutzer",
		revolutionaryAccount: "Revolutionary Accounts",
		legendAccount: "Legend Accounts",
		essentialAccount: "Essential Accounts",
		advancedAccount: "Advanced Accounts",
		unlimitedAccount: "Unlimited Accounts",
	},
}
