From specht@kulturbox.de  Thu Jun 20 08:35:23 1996
Date: Thu, 20 Jun 1996 08:35:17 +0200
From: Juergen Specht <specht@kulturbox.de>
Organization: KULTURBOX
X-Mailer: Mozilla 2.02 (WinNT; I)
MIME-Version: 1.0
To: andreas.koenig@mind.de, kun@pop.combox.de, 101762.2307@compuserve.com
Subject: [Fwd: Re: 34Mbit/s Netz]
Content-Type: multipart/mixed; boundary="------------70522FC73543"
X-Filter: mailagent [version 3.0 PL44] for k@.in-berlin.de

This is a multi-part message in MIME format.

--------------70522FC73543
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

-- 
Juergen Specht - KULTURBOX

--------------70522FC73543
Content-Type: message/rfc822
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

X-POP3-Rcpt: specht@trachea
Return-Path: hermes
Received: (from hermes@localhost) by kulturbox.netmbx.de (8.7.1/8.7.1) id SAA04513 for specht; Wed, 19 Jun 1996 18:30:12 +0200
Received: by netmbx.netmbx.de (/\==/\ Smail3.1.28.1)
	  from mail.cs.tu-berlin.de with smtp
	  id <m0uWPrO-0004wpC>; Wed, 19 Jun 96 18:12 MES
Received: (from nobody@localhost) by mail.cs.tu-berlin.de (8.6.12/8.6.12) id SAA12413; Wed, 19 Jun 1996 18:26:28 +0200
Resent-Date: Wed, 19 Jun 1996 18:26:28 +0200
Resent-Message-Id: <199606191626.SAA12413@mail.cs.tu-berlin.de>
Resent-From: nobody@cs.tu-berlin.de
Resent-To: kultur@kulturbox.netmbx.de
Received: from gatekeeper.telekom.de ([194.25.15.11]) by mail.cs.tu-berlin.de (8.6.12/8.6.12) with SMTP id SAA11678 for <specht@kulturbox.de>; Wed, 19 Jun 1996 18:11:29 +0200
Received: from ULM02.mnh.telekom.de by gatekeeper.telekom.de; (5.65v3.0/1.1.8.2/02Aug95-0132PM)
	id AA01376; Wed, 19 Jun 1996 18:11:27 +0200
Received: from ulm02.mnh.telekom.de (deuschle@mnh.telekom.de) by ULM02.mnh.telekom.de (8.6.10/3) with SMTP id SAA30680 for <specht@kulturbox.de>; Wed, 19 Jun 1996 18:14:40 GMT
Message-Id: <199606191814.SAA30680@ULM02.mnh.telekom.de>
X-Sender: deuschle@ulm02.mnh.telekom.de
X-Mailer: Windows Eudora Version 1.4.4
Mime-Version: 1.0
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable
Date: Wed, 19 Jun 1996 18:12:02 +0200
To: Juergen Specht <specht@kulturbox.de>
From: deuschle@mnh.telekom.de (Guenter Deuschle)
Subject: Re: 34Mbit/s Netz
X-Mozilla-Status: 0011

Hallo Herr Specht,
entschuldigen Sie vorab, dass ich Ihnen nicht telefonisch zur Verfuegung
stehe, ich Praesentationen gehalten/ noch zu halten und viele
Kundennachfragen zu projektieren. Nach Informationen des Produkt-Managers
Temme steht der POP schon zur Verf=FCgung! Standort: voraussichtlich:
Winterfeldstr. 21, 10781 Berlin.
Der POP hat zur Zeit direkte 34M-Anbindungen zu folgenden Orten: Rostock,
Hamburg, Hannover & Leipzig. 4 weitere werden in kuerze in Betrieb gehen.
Damit haben Sie einen Besonderen Sicherheitsstandard verfuegbar!
Kontakt muessen Sie ueber Ihre oerltliche Vertriebseinheit aufnehmen:
entweder den Geschaefts-Kunden-Vertrieb oder das GrossKundenManagement.
Diese Vertriebseinheiten greifen auf den oertlichen Technischen
Vertriebs-Support zu. Die Informationen werden ueber TVS zur Vertriebseiheit
gegeben und dann zu Ihnen.
 Sie benoetigen eine Standleitung von Ihrer Lokation zum Internet-POP
Uebergabepunkt zu Ihrem Info-Server ist ein CISCO 1000-Router. Dann zahlen
Sie neben den monatlichen Kosten fuer die Standleitung die Kosten fuer den
Internet-Zugang: zB bei 64k: 1500DM bei 2GByte Freivolumen. 128K: 3000 DM
bei 5 GB Freivolumen & 2M: 30.000 DM bei 50GB Freivolumen.
Freundliche Gruesse=20
Guenter Deuschle


>Sehr geehrter Herr Deuschle,
>Sie sind mir von Herrn Meyendriesch empfohlen worden.
>Ich versuche Informationen ueber das T-eigene 34Mbit/s Netz und den=20
>lokalen Pop-Berlin rauszufinden, bzw. was ein Anschluss kostet und=20
>wo man ihn herbekommt. Laut Herrn Schnick in Berlin gibt es den=20
>T-Pop nicht, laut Traceroute von Herrn Meyendriesch sehrwohl. Auch=20
>ist dies Netz in der IX vom Mai 96 erwaehnt.
>Koennen Sie mir helfen?
>
>MfG
>--=20
>Juergen Specht - KULTURBOX
>
>

=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=
=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=
=3D
Dipl.-Ing.  Guenter     D E U S C H L E
Deutsche Telekom AG     Niederlassung 3 Hannover
GrossKundenManagement - Techn. Vertriebs-Support:
Team-Leiter             Internet Online-Dienste
---------------------------------------------------
GrKM-TVS-IOD           Tel: +49-511-333-2772
Vahrenwalder-Str. 245  FAX: +49-511-333-2751
30179 Hannover       eMail: deuschle@mnh.telekom.de=20
=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=
=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=
=3D




--------------70522FC73543--



