Return-Path: eryq@rhine.gsfc.nasa.gov
Date: Wed, 20 Dec 95 19:59 CST
From: eryq@rhine.gsfc.nasa.gov
To: sitaram@selsvr.stx.com
Cc: johnson@killians.gsfc.nasa.gov,harvel@killians.gsfc.nasa.gov, eryq
Subject: Request for Leave

I will be taking vacation from Friday, 12/22/95, through 12/26/95.  
I will be back on Wednesday, 12/27/95.

Advance notice: I may take a second stretch of vacation after that, 
around New Year's.

Thanks,
 ____           __
|  _/__________/_/   Eryq (eryq@rhine.gsfc.nasa.gov)
|  _| _/ | | . |     Hughes STX Corporation, NASA/Goddard Space Flight Cntr.
|___|_|\_  |_  |___     
         | | |____/  http://selsvr.stx.com/~eryq/
         `-'
