Content-Type: text/plain; name=".signature"
Content-Disposition: inline; filename=".signature"
Content-Transfer-Encoding: x-gzip64
Mime-Version: 1.0
X-Mailer: MIME-tools 3.204  (ME 3.204 )
Subject: Testing!
Content-Length: 281

H4sIAJ+A5jIAA0VPTWvDMAy9+1e8nbpCsS877bRS1vayXdJDDwURbJEEEqez
VdKC6W+fnQ0iwdN7ktAHQEQAzV7irAv9DI8fvHLGD/bCobai7TisFUyuXxJW
lDB70aucxfHWtBxRnc4bfG+rrTmMztXBobrWlrHvu6YV7LwErVLZZP4n0IJA
K3J9N2aaJj3YqD2LeZYzFC75tlTaCtsg/SGRwmJZklnI1wOxa3wtt8Dgu2V2
EdIyAudnBvaOHd7Qd57ji/oFWju6Pg4BAAA=
