disabled_rules:
  - blanket_disable_command
  - colon
  - comma
  - comment_spacing
  - convenience_type
  - closure_parameter_position
  - cyclomatic_complexity
  - empty_parentheses_with_trailing_closure
  - file_length
  - force_cast
  - force_try
  - force_unwrapping
  - function_parameter_count
  - function_body_length
  - identifier_name
  - implicit_getter
  - legacy_objc_type
  - line_length
  - trailing_comma
  - trailing_whitespace
  - leading_whitespace
  - operator_whitespace
  - redundant_self_in_closure
  - return_arrow_whitespace
  - return_value_from_void_function
  - todo
  - type_body_length
  - vertical_whitespace
  - opening_brace

opt_in_rules:
- array_init
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_first_not_nil
- contains_over_range_nil_comparison
- discarded_notification_center_observer
- discouraged_assert
- discouraged_none_name
- discouraged_object_literal
- empty_collection_literal
- empty_string
- fallthrough
- fatal_error_message
- first_where
- flatmap_over_map_reduce
- force_unwrapping
- ibinspectable_in_extension
- joined_default_parameter
- last_where
- legacy_objc_type
- nslocalizedstring_key
- override_in_extension
- redundant_nil_coalescing
- redundant_self_in_closure
- reduce_into
- required_enum_case
- shorthand_optional_binding
- sorted_first_last
- static_operator
- test_case_accessibility
- toggle_bool
- unowned_variable_capture
- untyped_error_in_catch
- yoda_condition
- empty_xctest_method
- xct_specific_matcher

excluded:
- .idea
- fastlane
- releases
- tutanota.xcodeproj
- tutanota/build
- tutanota/tutanota-web
- tutanota/Sources/GeneratedIpc
- TutanotaSharedFramework/GeneratedIpc
- MockingbirdMocks
- MockingbirdSupport
