#  XCodeGen configuration file
name: tutanota # Also known as tutanooota (while testing xcodegen)
include:
  - path: "../xcodegen_common.yml"
options:
  useBaseInternationalization: true
  schemePathPrefix: "../" # Recommended for workspace based projects by XCodeGen devs
settings:
  base:
    PRODUCT_NAME: "tutanota"
    DEVELOPMENT_TEAM: "JKCH89Z3M9" # Tutao GmbH
    ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
settingGroups:
  codeSigning:
    base:
      CODE_SIGN_IDENTITY: "$(inherited)"
      CODE_SIGN_ENTITLEMENTS: "$(TARGET_NAME)/$(TARGET_NAME)$(CONFIGURATION).entitlements"
    configs:
      Debug Production:
        CODE_SIGN_ENTITLEMENTS: "$(TARGET_NAME)/$(TARGET_NAME).entitlements"
      Release Development:
        PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]: "match AdHoc de.tutao.tutanota.$(PRODUCT_NAME)"
      Release Staging:
        PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]: "match AdHoc $(PRODUCT_BUNDLE_IDENTIFIER)"
      Release Production:
        CODE_SIGN_ENTITLEMENTS: "$(TARGET_NAME)/$(TARGET_NAME).entitlements"
        PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]: "match AdHoc $(PRODUCT_BUNDLE_IDENTIFIER)"
  extension:
    base:
      SKIP_INSTALL: "YES"
      INFOPLIST_KEY_CFBundleDisplayName: "$(TARGET_NAME)"
      LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
      SWIFT_EMIT_LOC_STRINGS: "YES"
      GENERATE_INFOPLIST_FILE: "YES"
      CURRENT_PROJECT_VERSION: "1"
      MARKETING_VERSION: "1.0"
targets:
  tutanota:
    templates: ["formatAndLint"]
    type: "application"
    sources:
      - path: "tutanota"
        excludes:
          [
            "tutanota-web",
            "Sources/sdktest.swift",
          ]
        # XCode will not resolve symbolic links when adding a folder reference, so we will just use a relative path
      - path: "../build"
        name: "build"
        type: "folder"
        buildPhase: "resources"
      - path: "Plans.storekit"
    settings:
      base:
        PRODUCT_MODULE_NAME: "tutanota"
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/Frameworks"
        INFOPLIST_FILE: "tutanota/Info.plist"
        SWIFT_OBJC_BRIDGING_HEADER: "tutanota/Sources/tutanota-Bridging-Header.h"
        HEADER_SEARCH_PATHS:
          [
            "${PROJECT_DIR}/tutanota/include",
          ]
        CLANG_CXX_LANGUAGE_STANDARD: "gnu++14"
        GCC_PREPROCESSOR_DEFINITIONS: ["SQLITE_HAS_CODEC=1", "$(inherited)"]
        OTHER_CFLAGS[arch=*]:
          [
            "-DSQLITE_HAS_CODEC",
            "-DSQLITE_TEMP_STORE=3",
            "-DSQLCIPHER_CRYPTO_CC",
            "-DNDEBUG",
          ]
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: "NO"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: "NO"
      configs:
        Debug Development:
          PRODUCT_NAME: "Tuta D"
        Debug Staging:
          PRODUCT_NAME: "Tuta Test"
        Debug Production:
          PRODUCT_NAME: "Tuta Mail"
        Release Development:
          PRODUCT_NAME: "Tuta D"
        Release Staging:
          PRODUCT_NAME: "Tuta Test"
          PROVISIONING_PROFILE_SPECIFIER: "match AdHoc de.tutao.tutanota.test"
          PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]: "match AdHoc de.tutao.tutanota.test 1716556941"
        Release Production:
          PRODUCT_NAME: "Tuta Mail"
      groups:
        - "codeSigning"
    dependencies:
      - package: Atomics
      - sdk: CryptoTokenKit.framework
        embed: false
      - package: DictionaryCoding
      - sdk: Foundation.framework
        embed: false
      - sdk: Security.framework
        embed: false
      - target: TutanotaNotificationExtension
        codeSign: false
      - target: TutanotaSharedFramework
      - target: TutanotaShareExtension
        codeSign: false
      - framework: tutasdk.framework
        embed: false
      - framework: StoreKit.framework
        embed: false
  tutanotaTests:
    templates: ["formatAndLint"]
    type: "bundle.unit-test"
    sources:
      - path: "tutanotaTests"
        excludes: ["CompatibilityTest.m"]
      - path: "tutanotaTests"
        includes: ["CompatibilityTest.m"]
        compilerFlags: "-Itutanota/include"
    settings:
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"
      CODE_SIGN_STYLE: "Automatic"
      LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
      BUNDLE_LOADER: "$(TEST_HOST)"
      INFOPLIST_FILE: "tutanotaTests/Info.plist"
      PRODUCT_BUNDLE_IDENTIFIER: "de.tutao.tutanotaTests"
      PRODUCT_NAME: "$(TARGET_NAME)"
      HEADER_SEARCH_PATHS:
        [
          "${PROJECT_DIR}/tutanota/include",
        ]
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Tuta D.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Tuta D"
      SWIFT_OBJC_BRIDGING_HEADER: "tutanotaTests/tutanotaTests-Bridging-Header.h"
      SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: "NO"
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: "NO"
      CLANG_CXX_LANGUAGE_STANDARD: "gnu++14"
    dependencies:
      - target: "tutanota"
  TutanotaShareExtension:
    templates: ["formatAndLint"]
    type: "app-extension"
    sources: "TutanotaShareExtension"
    settings:
      base:
        PRODUCT_NAME: "TutanotaShareExtension"
        PRODUCT_BUNDLE_IDENTIFIER: "$(inherited).TutanotaShareExtension"
        IPHONEOS_DEPLOYMENT_TARGET: "15.5" # Why?
        INFOPLIST_FILE: "TutanotaShareExtension/Info.plist"
        HEADER_SEARCH_PATHS: '"${PROJECT_DIR}/tutanota/include"/**'
        MARKETING_VERSION: "3.104.5"
        CLANG_CXX_LANGUAGE_STANDARD: "gnu++17"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: "NO"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: "NO"
      groups:
        - "codeSigning"
        - "extension"
    dependencies:
      - target: "TutanotaSharedFramework"
      - framework: tutasdk.framework
        embed: false
  TutanotaSharedFramework:
    type: "framework"
    platform: "iOS"
    sources:
      - path: "TutanotaSharedFramework"
        headerVisibility: "public"
        # Exclude TUTBigNum.h so we change it's visiblity to 'project' in another source
        excludes: ["Crypto/TUTBigNum.h", "*.md", "Sql/sqlite3.c"]
      - path: "TutanotaSharedFramework/Crypto"
        includes: ["TUTBigNum.h"]
        headerVisibility: "project"
      - path: "TutanotaSharedFramework/Sql"
        # Don't show warnings for vendored code
        includes: ["sqlite3.c"]
        compilerFlags: "-w"
    settings:
      PRODUCT_NAME: "TutanotaSharedFramework"
      PRODUCT_BUNDLE_IDENTIFIER: "$(inherited).TutanotaSharedFramework"
      INSTALL_PATH: "$(LOCAL_LIBRARY_DIR)/Frameworks"
      GCC_PREPROCESSOR_DEFINITIONS: ["SQLITE_HAS_CODEC=1", "$(inherited)"]
      OTHER_CFLAGS:
        [
          "-DSQLITE_HAS_CODEC",
          "-DSQLITE_TEMP_STORE=3",
          "-DNDEBUG",
          "-DSQLCIPHER_CRYPTO_CC",
        ]
      APPLICATION_EXTENSION_API_ONLY: "YES"
      ENABLE_USER_SCRIPT_SANDBOXING: "YES"
      SKIP_INSTALL: "YES"
      DYLIB_COMPATIBILITY_VERSION: "1"
      DYLIB_CURRENT_VERSION: "1"
      DYLIB_INSTALL_NAME_BASE: "@rpath"
      LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
      LOCALIZATION_PREFERS_STRING_CATALOGS: "YES"
      SWIFT_EMIT_LOC_STRINGS: "YES"
      DEFINES_MODULE: "YES"
      GENERATE_INFOPLIST_FILE: "YES"
      CODE_SIGN_STYLE: "Manual"
      CODE_SIGN_IDENTITY: "$(inherited)"
      PROVISIONING_PROFILE_SPECIFIER: ""
      CURRENT_PROJECT_VERSION: "1"
      MARKETING_VERSION: "1.0"
      VERSIONING_SYSTEM: "apple-generic"
      GCC_NO_COMMON_BLOCKS: "YES"
      CLANG_CXX_LANGUAGE_STANDARD: "gnu++20"
      ENABLE_MODULE_VERIFIER: "YES"
      MODULE_VERIFIER_SUPPORTED_LANGUAGES: "objective-c objective-c++"
      MODULE_VERIFIER_SUPPORTED_LANGUAGE_STANDARDS: "$(GCC_C_LANGUAGE_STANDARD) $(CLANG_CXX_LANGUAGE_STANDARD)"
      SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: "NO"
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: "NO"
      ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: "YES"
    dependencies:
      - package: DictionaryCoding
        product: "DictionaryCoding"
  TutanotaNotificationExtension:
    type: "app-extension"
    platform: "iOS"
    sources:
      - path: "TutanotaNotificationExtension"
    settings:
      base:
        PRODUCT_NAME: "$(TARGET_NAME)"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: "NO"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: "NO"
        GCC_NO_COMMON_BLOCKS: "YES"
        CLANG_CXX_LANGUAGE_STANDARD: "gnu++20"
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: "YES"
        ENABLE_USER_SCRIPT_SANDBOXING: "YES"
        LOCALIZATION_PREFERS_STRING_CATALOGS: "YES"
        INFOPLIST_FILE: "TutanotaNotificationExtension/Info.plist"
        GENERATE_INFOPLIST_FILE: "NO"
        PRODUCT_BUNDLE_IDENTIFIER: "$(inherited).TutanotaNotificationExtension"
      groups:
        - "codeSigning"
        - "extension"
    dependencies:
      - target: "TutanotaSharedFramework"
      - framework: tutasdk.framework
        embed: false
  TutanotaSharedTests:
    type: "bundle.unit-test"
    platform: "iOS"
    sources:
      - path: "TutanotaSharedTests"
      - path: "MockingbirdMocks/TutanotaSharedTests-TutanotaSharedFrameworkMocks.generated.swift"
        optional: true # The file will be generated in the "Generate Mockingbird Mocks" stage
    settings:
      GCC_NO_COMMON_BLOCKS: "YES"
      CLANG_CXX_LANGUAGE_STANDARD: "gnu++20"
      ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: "YES"
      IPHONEOS_DEPLOYMENT_TARGET: "15.5"
      LOCALIZATION_PREFERS_STRING_CATALOGS: "YES"
      SWIFT_EMIT_LOC_STRINGS: "YES"
      GENERATE_INFOPLIST_FILE: "YES"
      PRODUCT_NAME: "$(TARGET_NAME)"
      CODE_SIGN_STYLE: "Automatic"
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Tuta D.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Tuta D"
      CURRENT_PROJECT_VERSION: "1"
      MARKETING_VERSION: "1.0"
    dependencies:
      - target: "tutanota"
      - target: "TutanotaSharedFramework"
        embed: false
      - package: "Mockingbird"
      - framework: tutasdk.framework
        embed: false
    preBuildScripts:
      - path: "buildScripts/generate-mockingbird.sh"
        name: "Generate Mockingbird Mocks"
        shell: "/bin/sh"
        showEnvVars: true
        basedOnDependencyAnalysis: false
        outputFiles:
          [
            "$(SRCROOT)/MockingbirdMocks/TutanotaSharedTests-TutanotaSharedFrameworkMocks.generated.swift",
          ]
targetTemplates:
  formatAndLint:
    type: "application"
    platform: "iOS"
    supportedDestinations: ["iOS"]
    preBuildScripts:
      - path: "buildScripts/format.sh"
        name: "Check formating with swift-format"
        shell: "/bin/sh"
        showEnvVars: true
        basedOnDependencyAnalysis: false
    postCompileScripts:
      - path: "buildScripts/lint-xcode.sh"
        name: "Lint with SwiftLint"
        shell: "/bin/sh"
        showEnvVars: true
        basedOnDependencyAnalysis: false
schemes:
  tuta debug:
    build:
      targets:
        tutanota: ["analyze", "test", "run", "profile"]
        tutanotaTests: ["test"]
    run:
      config: "Debug Development"
      storeKitConfiguration: "Plans.storekit"
    test:
      config: "Debug Development"
      targets: ["tutanotaTests"]
    archive:
      config: "Release Development"
  tuta staging:
    build:
      targets:
        tutanota: "all"
        tutanotaTests: ["test"]
    run:
      config: "Debug Staging"
      storeKitConfiguration: "Plans.storekit"
    test:
      config: "Debug Staging"
      targets: ["tutanotaTests"]
    archive:
      config: "Release Staging"
  tuta prod:
    build:
      targets:
        tutanota: "all"
        tutanotaTests: ["test"]
    run:
      config: "Debug Production"
      storeKitConfiguration: "Plans.storekit"
    test:
      config: "Debug Production"
      targets: ["tutanotaTests"]
    archive:
      config: "Release Production"
  TutanotaShareExtension:
    build:
      targets:
        TutanotaShareExtension: "all"
  TutanotaSharedFramework:
    build:
      targets:
        TutanotaSharedFramework: "all"
        TutanotaSharedTests: ["test"]
    test:
      targets: ["TutanotaSharedTests"]
packages:
  DictionaryCoding:
    url: https://github.com/elegantchaos/DictionaryCoding.git
    version: 1.0.9
  Mockingbird:
    url: https://github.com/birdrides/mockingbird.git
    version: 0.20.0
  Atomics:
    url: https://github.com/apple/swift-atomics.git
    version: 1.0.2
