"use strict";

tutao.provide('tutao.tutanota.ctrl.LanguageViewModel');

/**
 * Provides all localizations of strings on our gui.
 * @constructor
 */
tutao.tutanota.ctrl.LanguageViewModel = function() {
	tutao.util.FunctionUtils.bindPrototypeMethodsToThis(this);
	var lang = null; // tutao.tutanota.util.LocalStore.load('language');
	if (!lang) {
		lang = tutao.tutanota.util.ClientDetector.getDefaultLanguage();
	}
	this._current = ko.observable(lang);
};

/**
 * Provides the current language, one of "en" and "de"
 * @return {string} The current language.
 */
tutao.tutanota.ctrl.LanguageViewModel.prototype.getCurrentLanguage = function() {
	return this._current();
};

/**
 * Sets the current language.
 * @param {string} lang The language to set, one of "en" and "de".
 */
tutao.tutanota.ctrl.LanguageViewModel.prototype.setCurrentLanguage = function(lang) {
	if (lang != "en" && lang != "de") {
		throw new Error("invalid language: " + lang);
	}
	// tutao.tutanota.util.LocalStore.store('language', lang);
	this._current(lang);
};

/**
 * Provides the text with the given id and the given params in the currently selected language.
 * @param {string} id One of the ids defined in tutao.tutanota.ctrl.LanguageViewModel.en or tutao.tutanota.ctrl.LanguageViewModel.de.
 * @param {Object<String,String>=} params An object whose property keys are the strings that shall be replaced by the corresponding property value in the text.
 * @return {string} The text.
 */
tutao.tutanota.ctrl.LanguageViewModel.prototype.get = function(id, params) {
	if (id == null) {
		return "";
	}
	var text = tutao.tutanota.ctrl.LanguageViewModel[this._current()][id];
	if (!text) {
		throw new Error("no translation found for id " + id);
	}
	if (params instanceof Object) {
		for (var param in params) {
			text = text.replace(param, params[param]);
		}
	}
	return text;
};

/**
 * Returns all translations in pretty-printed form.
 */
tutao.tutanota.ctrl.LanguageViewModel.prototype.allTranslationsAsJson = function() {
	return JSON.stringify({de: tutao.tutanota.ctrl.LanguageViewModel.de, en: tutao.tutanota.ctrl.LanguageViewModel.en}, null, 2)
};

/**
 * Defines the English translations of all texts in Tutanota.
 * The actual identifier is in camel case and the type is appended by an underscore.
 * Types: label, action, msg, title, alt, placeholder
 */
tutao.tutanota.ctrl.LanguageViewModel.en = {
	// soft-hyphen: \u00AD
		
	// mail
	deleteMail_msg:	"Delete new email without sending?",
	tooBigAttachment_msg: "The following files could not be attached because the overall size exceeds 25 MB: ",
	received_action: "Inbox",
	receivedMail_alt: "Received email",
	receivedMails_alt: "Received emails",
	sent_action: "Sent",
	sentMail_alt: "Sent email",
	sentMails_alt: "Sent emails",
	trash_action: "Trash",
	trashedMail_alt: "Deleted email",
	trashedMails_alt: "Deleted emails",
	mailWithAttachment_alt: "Email with attachment",
	meNominative_label: "Me",
	meDativ_label: "Me",
	meAccusative_label: "Me",
	from_label: "From",
	to_label: "To",
	cc_label: "Cc",
	bcc_label: "Bcc",
	ccBcc_label: "B/Cc",
	closedLock_alt: 'Closed lock',
	openedLock_alt: 'Open lock',
	attachFiles_action: "Attach files",
	removeAttachment_alt: "Remove attachment",
	passwordTransmission_label: "Password transmission",
	atLeastOneMobileNumber_label: "At least one mobile phone number or an agreed password is needed for each external recipient.",
    preSharedPasswordNeeded_label: "Please enter an agreed password for each external recipient.",
    autoTransmitPasswordDeactivated_label: "Password transmission by text message is currently not supported.",
	secureMail_title: 'Email is encrypted for external recipients.',
	unsecureMail_title: 'Email is not encrypted for external recipients.',
	noRecipients_msg: 'Please enter the email address of your recipient.',
	invalidRecipients_msg: 'Please correct the invalid email addresses\n in the recipient fields.',
	noSubject_msg: 'Please enter a subject.',
	noPasswordChannels_msg: 'Please provide a mobile phone number or an agreed password for all external recipients.',
    noPreSharedPassword_msg: 'Please provide an agreed password for all external recipients.',
	invalidPasswordChannels_msg: 'Please check the password channels again for invalid phone numbers.',
	maxSizeExceeded_msg: "The maximum message size of $ to insecure external recipients is exceeded.",
	send_action: "Send",
	reply_action: "Reply",
	replyAll_action: "Reply all",
	forward_action: "Forward",
	replyConfidential_action: "Reply confidentially",
    export_action: "Export",
    deleteTrash_action: "Delete all",
	by_label: "by",
	date_label: "Date",
	subject_label: "Subject",
    confidential_label: "Confidential",
	showQuotation_action: "+ Quotes",
	hideQuotation_action: "- Quotes",
	legacyNoReplyIe_msg: "This Internet Explorer is an old version and does not support replying to or exporting of emails. If you need this feature, please update or use one of the following browsers:",
	legacyNoAttachmentsIeMobile_msg: "Internet Explorer mobile does not support downloading attachments or attaching files to emails. If you need these features, please use one of the following browsers:",
	legacyNoReplyAndroid_msg: "The Android browser does not support replying to emails or saving attachments to disk. Still some file types can be displayed in the browser. Please use one of the following browsers otherwise:",
	legacyDownloadNotPossible_msg: "Safari does not support exporting emails or saving attachments to disk. Still some file types can be displayed in the browser. Please use one of the following browsers otherwise:",
	clickToSave_label: "Click to save",
	confidential_action: "Confidential",
	nonConfidential_action: "Not confidential",
    confidentialStatus_msg: "This message is sent end-to-end encrypted.",
    confidentialSwitchableStatus_msg: "This message is sent end-to-end encrypted.",
    nonConfidentialStatus_msg: "This message is not sent end-to-end encrypted.",
	noMails_msg: "There are no emails in this list.",
	noMail_msg: "No email selected.",
	addMobileNumber_msg: "Add an additional mobile phone number.",
	setPresharedPassword_action: "Set agreed password",
	presharedPassword_label: "Agreed password",
	mobileNumberNotValid_msg: "Invalid format.",
	fromAddressBook_label: "From address book: ",
	presharedPasswordNotStrongEnough_msg: "At least one of the entered passwords is not secure enough. Send the email anyway?",
    showAttachment_label: "Display attachment",
	saveDownloadNotPossibleSafariDesktop_msg: "Safari does not support saving attachments to disk. Still some file types can be displayed in the browser by clicking the link above. Please use Mozilla Firefox or Google Chrome otherwise.",
	saveDownloadNotPossibleSafariMobile_msg: "Safari does not support saving attachments to disk. Still some file types can be displayed in the browser by clicking the link above. Please use a desktop browser otherwise.",
	saveDownloadNotPossibleAndroid_msg: "The native Android browser does not support saving attachments to disk. Still some file types can be displayed in the browser by clicking the link above. Please install Google Chrome or Opera otherwise.",
	saveDownloadNotPossibleIe_msg: "The mobile Internet Explorer does not support saving or displaying attachments. Please use a desktop browser for these features.",
	addAttachmentNotPossibleIe_msg: "The mobile Internet Explorer does not support adding attachments to emails. Please use a desktop browser for this feature.",
	downloadAttachmentNotPossible_msg: "Unfortunately, downloading this attachment is not possible. Attachments bigger than 7 MB are currently not supported on this device.",
    removeRecipient_alt: "Remove recipient",
	couldNotAttachFile_msg: "The file could not be loaded.",
    changeNotificationMailLanguage_msg: "Language of notification email:",
    reallySubmitContent_msg: "Do you really want to send the entered data to an external site?",
    search_title: "Search",
	loadMoreMails_action: "Load more emails",
    confirmDeleteTrash_msg: "Do you really want to delete all mails from the trash?",
	newMails_msg: "New Tutanota email received.",
    newMailBadge_msg: "1 new email received",
    newMailsBadge_msg: "%d new emails received",
    passwords_label: "Passwords",
    showPasswordChannelColumn_title: "Enter passwords for external recipients.",
    confidentialMail_alt: "This email was transmitted end-to-end encrypted.",

    //invitation
    invitationMailSubject_msg: "Join Tutanota and fight for privacy!",
    invitationMailBody_msg: "Hello!<br><br>I would like to invite you to Tutanota. With the free email service from Germany we are able to easily send end-to-end encrypted emails. Let’s communicate confidentially and fight against mass surveillance of the internet!<br><br>Simply sign up here:<br><a href=\"https://app.tutanota.de/#register\">https://app.tutanota.de/#register</a><br><br>I am looking forward to receiving your first encrypted email.<br><br>Cheers,<br>$<br><br>PS: Tutanota encrypts all our data automatically, in addition it is open source: <a href=\"https://github.com/tutao/tutanota\">https://github.com/tutao/tutanota</a>",

	// contact
	discardContact_msg: "Discard new contact?",
	discardContactChanges_msg: "Discard contact modifications?",
	discardContactChangesFor_msg: "Discard contact modifications for $?",
	deleteContact_msg: "Are you sure you want to delete this contact?",
	private_label: "Private",
	mobile_label: "Mobile",
	fax_label: "Fax",
	work_label: "Work",
	other_label: "Other",
	custom_label: "Custom",
	twitter_label: "Twitter",
	facebook_label: "Facebook",
	xing_label: "Xing",
	linkedin_label: "Linked in",
	email_label: "Email",
	phone_label: "Phone",
	address_label: "Address",
	social_label: "Social",
	comment_label: "Comment",
	birthday_alt: "Birthday",
	contactImage_alt: "Picture",
	removePhoneNumber_alt: "Remove phone number",
	removeMailAddress_alt: "Delete this email address",
	removeAddress_alt: "Delete this address",
	removeSocial_alt: "Delete this social id",
	sendMail_alt: "Send email to this address",
	callNumber_alt: "Call this number",
	showAddress_alt: "Show this address in google maps",
	openSocial_alt: "Open this social account",
	firstName_placeholder: "First name",
	lastName_placeholder: "Last name",
	birthdayWithFormat_placeholder: "Birthday (dd.mm.yyyy)",
	company_placeholder: "Company",
	title_placeholder: "Title",
	noContacts_msg: "There are no contacts in this list.",
	noContact_msg: "No contact selected.",
	passwordsHeading_label: "Passwords:",
	presharedPasswordHeading_label: "Agreed:",
	autoTransmitPasswordHeading_label: "Text message:",
	showPassword_alt: "Keep button pressed to show the password.",

	// settings
	accountSettings_action: "Account",
	securitySettings_action: "Security",
	changePasswordSettings_action: "Change password",
	adminUserList_action: "User management",
    adminDeleteAccount_action: "Delete account",
	adminUserAdd_action: "Add user",
    adminPremiumFeatures_action: "Extensions",
    adminMessages_action: "Displayed messages",
	action_label: "Action",
	edit_label: "Edit",
	editUser_label: "Edit user",
	save_msg: "Saving data ...",
    saved_msg: "Saved successfully!",
	state_label: "State",
	create_action: "Create",
    createActionSuccess_msg: "All accounts have been created successfully.",
    createActionFailed_msg: "Failed to create an account. Please try again later.",
    createActionStatus_msg: "Creating users... Finished ${index} of ${count} accounts.",
	import_action: "Import",
	importCsv_label: "Import CSV data",
	importCsvInvalid_msg: "The CSV data is invalid (line $).",
	successfullyCreatedUsers_msg: "The following users have been created successfully. Please note down the passwords carefully and provide them to the users.",
    deleted_label: "Deleted",
    created_label: "Created",
	addinInfoText_msg: "Download the Outlook Addin for Tutanota Starter here. Updates are automatically installed when Outlook starts.",
    promotionCodeEnterNeutral_msg:"Please enter your promotion code to activate the storage extension.",
    promotionCodeEnterWrongFormat_msg: "Invalid promotion code format.",
    promotionCodeEnterValidFormat_msg: "Valid promotion code format.",
    promotionCodeInvalid_msg: "The promotion code is invalid.",
	promotionCodeSuccess_msg: "Extension has been successfully activated.",
    storageCapacity5GB_label: "5GB storage capacity",
    storageCapacity_label: "Storage capacity",
    activate_action:"Activate",
    externalWelcomeMessage_label: "Welcome message",
    externalWelcomeMessageInfo_msg: "This message is displayed to external recipients of all users in the Tutanota menu bar. You may e.g. enter your company's name.",
    externalWelcomeMessagePreview_label: "Preview",
    externalWelcomeMessagePreviewInfo_msg: "This is how external users see the message.",
    externalWelcomeMessageUpdated_msg: "Message was updated.",
    externalWelcomeMessageFree_msg: "This version of Tutanota is a service for private users.",
    storageCapacityNoLimit_label: "unlimited",

	// account settings
	accountType_label: "Account type",
	mailName_label: "Sender name",
	mailNameInfo_msg: "This name is shown to the recipients of your emails. You can change it in the user management.",

	// security settings
	lastSuccessfulLogin_label: "Last successful login",
	lastSuccessfulLoginInfo_msg: "The time of your last successful login before the current one.",
	failedLogins_label: "Failed logins",
	failedLoginsInfo_msg: "The number of failed login attempts since your last successful login.",

	// change password
	oldPassword_label: "Old password",
	oldPasswordNeutral_msg: "Please enter your old password.",
	oldPasswordInvalid_msg: "Incorrect password.",
	newPassword_label: "New password",
	securePasswords_link: "https://en.wikipedia.org/wiki/Password_strength#Guidelines_for_strong_passwords",
	password1Neutral_msg: "Please enter a password.",
	password1InvalidSame_msg: "The new password is the same as the old one.",
	password1InvalidUnsecure_msg: "Password is not secure enough.",
    password1InvalidTooShort_msg: "Password is too short.",
	password2Neutral_msg: "Please confirm your password here.",
	password2Invalid_msg: "Confirmed password is different.",
	verificationCode_msg: "You will receive the verification code via text message.",
	code_label: "Verification code",
	pwChangeValid_msg: "Password was changed.",
	pwChangeInvalidTooManyVerifyAttempts_msg: "Number of allowed attempts exceeded. Please try again later.",
	pwChangeInvalidTooManyChangeAttempts_msg: "Your password was changed too often. Please try again later.",
	pwChangeButtonSendCode_action: "Send code",
	pwChangeButtonChangePw_action: "Change password",
	serverNotReachable_msg: "Could not reach server, looks like you are offline. Please try again later.",
    outdatedClient_msg: "Please update Tutanota. The currently installed version is too old and not supported any longer.",
    unknownError_msg: "An unexpected error occurred. Please try again later.",
	passwordNotChanged_msg: "The password was not changed.",
    passwordResetFailed_msg: "An error occurred. The password was not changed.",
	notePassword_msg: "Please note down the password carefully and provide it to the user.",
    changePasswordNotSupported_msg: "For security reasons password change is not supported on mobile devices.",

    // delete account
    deleteAccountReason_label: "Why?",
    deleteAccountReasonInfo_msg: "Optional: We would appreciate it if you gave us a reason why you want to delete the account so that we can improve Tutanota further.",
    deleteAccountInfo_msg: "Your complete account will be deleted.",
    deleteAccountConfirm_msg: "Do you really want to delete your account?",
    deleteAccountWait_msg: "Account is being deleted...",
    deleteAccountDeleted_msg: "Your account is deleted now.",

	// general
	emptyString_msg: "\u2008", // an empty string or normal whitespace makes a label collapse, so enter this invisible character
	save_action: "Save",
	dismiss_action: "Cancel",
	cancel_action: "Cancel",
	edit_action: "Edit",
	delete_action: "Delete",
	undelete_action: "Restore",
    finalDelete_action: "Delete",
	print_action: "Print",
	back_action: "Back",
	ok_action: "Ok",
    newMail_action: "New email",
	monthNames_label: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
	weekDays_label: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
	yesterday_label: "yesterday",
	busy_alt: "Busy",
	close_alt: "Close",
	german_alt: "Deutsch",
	english_alt: "English",
	check_msg: "Checking...",
	add_action: "Add", // also used by outlook addin
	remove_action: "Remove", // also used by outlook addin
	notFound404_msg: "Sorry, but the page you are looking for has not been found. Try checking the URL for errors and hit the refresh button of your browser.",
    loading_msg: "Loading...",
    show_action: "Show",
    applicationUpdate_label: "Loading Tutanota...",
    leavePageConfirmation_msg: "Do you really want to leave Tutanota?",
    loadMore_action: "Load more",
    newContact_action: "New contact",
    password_label: 'Password',
    passwordEnterNeutral_msg: "Please enter your password for confirmation.",
    passwordWrongInvalid_msg: "Your password is wrong.",
    passwordValid_msg: "Password ok.",

	// code verification
	codeNeutralEnterCode_msg: "Please enter the verification code.",
	codeValid_msg: "Code format ok.",
	codeInvalid_msg: "Incorrect code. Please check again.",

	// external login
	receiveMsg_label: "Receive message",
	invalidLink_msg: "Sorry, this link is not valid.",
	expiredLink_msg: "Sorry, this link is not valid anymore. You should have received a new notification email with the currently valid link. Previous links are deactivated for security reasons.",
	sendSms_action: "Send text message",
	smsError_msg: "Could not send text message.",
	smsSent_msg: "The text message should arrive in the next 60s.",
	smsResent_msg: "If no text message has arrived you can resend it now.",
	smsSentOften_msg: "Too many sent text messages. Please ask the sender of the message to resend it.",
	invalidPassword_msg: "Invalid password. Please check it again.",
	showMail_action: "Show mailbox",
	chooseNumber_msg: "Please click on one of the \"Send SMS\" buttons below. The Tutanota password for your mailbox will be sent to the given number (maximum of three text messages).",
	clickNumber_msg: "Please click on the \"Send SMS\" button below. The Tutanota password for your mailbox will be sent to the given number (maximum of three text messages).",
	storePassword_action: "Store password",
	enterPresharedPassword_msg: "Please enter the password which you have agreed upon with the sender.",
	sendingSms_msg: "Sending SMS...",
	onlyPrivateComputer_msg: "Only choose this option if you are using a private device.",
	loadingMail_msg: "Loading mailbox...",
	enterSmsPassword_msg: "Please enter the password that has been transmitted via text message here or click on the link within the text message.",

	// login
	welcome_msg: "Login",
	afterRegistration_msg: "Your account has been created! Login - and enjoy!",
	loginFailedOften_msg: "Too many failed login attempts. Please try again later.",
	loginFailed_msg: "Invalid login credentials. Please try again.",
	login_action: "Log in",
	login_msg: "Logging in.",
	mailAddress_label: "Email address",
	socialMedia_label: "If you like us, like us:",

    appInfoAndroidUrl_action: "https://play.google.com/store/apps/details?id=de.tutao.tutanota",
    appInfoIosUrl_action: "https://itunes.apple.com/app/tutanota/id922429609?ls=1&mt=8",
    appInfoAndroidImage_action: "graphics/android_en.png",
    appInfoIosImage_action: "graphics/ios_en.png",
    appInfoAndroidImageAlt_alt: "Android app on Google Play",
    appInfoIosImageAlt_alt: "iOS app on Apple store",

	// header
	logo_alt: "Tutanota logo",
	featureNotAvailable_msg: "This feature will be available in 2014!",
	emails_label: "Emails",
	emails_alt: "Emails",
	newMail_alt: "New Email",
	contacts_label: "Contacts",
	contacts_alt: "Contacts",
	newContact_alt: "New Contact",
	newFolder_alt: "New Folder",
	files_alt: "Files",
	files_label: "Files",
	calendar_label: "Calendar",
	calendar_alt: "Calendar",
	tasks_label: "Tasks",
	tasks_alt: "Tasks",
	feedback_label: "Feedback",
	feedback_alt: "Feedback",
	logout_label: "Logout",
	logout_alt: "Logout",
    dev_label: "Developer",
	settings_label: "Settings",
	settings_alt: "Settings",
    register_label: "Register",
    register_alt: "Register",
    invite_label: "Invite",
    invite_alt: "Invite",
    more_label: "More",
    dots_label: "...",
    folderTitle_label: "Folders",

    //admin
    logs_label: "logs",
    db_label: "db",
    monitor_label: "monitor",
    config_label: "config",
    customers_label: "customers",

	// not supported
	for_label: "for",
	oldBrowser_msg: "Oh! We are sorry. Unfortunately, you are using an outdated browser. Please upgrade to the latest version of one of the following browsers:",
	unsupportedBrowser_msg: "Oh! We are sorry. Unfortunately, your browser is not supported. Please use one of the following browsers:",
	browserNoKeygen_msg: "Thank you for choosing Tutanota as your future mail client. During the registration process secure keys are being generated. Unfortunately the key generation needs more performance than your currently used browser or device may provide. Please use one of the following browsers on a desktop or laptop computer:",
	thanks_msg: "Thank you for your cooperation.\nYour team from Tutanota",
	claim_label: "Tutanota - mail. done. right.",

	// registration
    regLinkInvalid_msg: "Sorry, this registration link is not valid.",
    regDisabledFree_msg: "The number of Tutanota Free users is limited and registration currently disabled. Please follow us here, to get notified as soon as registration is possible again:",
    regDisabledStarter_msg: "The number of Tutanota Starter users is limited and registration currently disabled. Please signup here, to get notified as soon as registration is possible again:",
	registrationHeadline_msg: "Tutanota Registration",
    registrationHeadlineBeta_msg: "Tutanota Beta Registration",
    registrationSubHeadline1_msg: "Verify domain (step 1 of 2)",
    registrationSubHeadline2_msg: "Enter registration data (step 2 of 2)",
	company_label: "Company",
	domain_label: "Domain",
    currentMailAddress_label: "Your mail address",
    currentMailAddressAdmin_label: "Mail address of the administrator",
	companyNameNeutral_msg: "Please enter company name.",
	companyNameValid_msg: "Company name ok.",
	verifyingCode_msg: "Verifying code. Please wait.",
	sendingSms_alt: "Sending SMS. Please wait.",
	creatingAccount_alt: "Creating account. Please wait.",
	domainInfo_msg: "Please confirm, that you are allowed to administer this domain.",
	loginNameInfo_msg: "Your name.",
    loginNameInfoAdmin_msg: "Optional: the user's name.",
    loginNameInfoFree_msg: "Optional: This name is shown to recipients of your emails.",
	mobileNumberInfo_msg: "Please include a '+' and your <a href=\"https://en.wikipedia.org/wiki/List_of_mobile_phone_codes_by_country\" target=\"_blank\">country code</a>, .e.g +4917012345678. Your mobile phone number is needed to authorize you when you want to change your password.",
	mobileNumberNeutral_msg: "Please enter your mobile phone number.",
	mobileNumberValid_msg: "Mobile phone number looks ok.",
	mobileNumberInvalid_msg: "Mobile phone number is not valid.",
    mobileNumberNoCountryCode_msg: "Country code is missing, e.g. +49 for Germany.",
    currentMailAddressInfo_msg: "This address will be used for verifying that you are the owner or administrator of this domain.\nHint: Use a postmaster@<your_domain> or hostmaster@<your_domain> address to be able to register immediately (automatic verification). A manual verification is needed for all other addresses, which may take up to one work day.",
	mailAddressInfo_msg: "This will be your new mail address. Register with a unique name. First come, first serve. At least four letters required.",
    mailAddressInfoBusiness_msg: "This is your email address.",
    mailAddressInfoAdmin_msg: "The user's mail address.",
	mailAddressNeutral_msg: "Please enter mail address.",
    mailAddressValid_msg: "Mail address is valid.",
	mailAddressInvalid_msg: "Mail address is not valid.",
	mailAddressAvailable_msg: "Email address is available.",
	mailAddressNA_msg: "Email address is not available.",
    mailAddressDelay_msg: "Too many requests, please try again later.",
	mailAddressBusy_msg: "Verifying email address...",
	pwStrength_title: "This shows the security level of your entered password.",
	goodPassphrase_action: "How to find a good password?",
    passwordImportance_msg: "Please store this password in a secure place. We are not able to restore your password or to reset your account because all of your data is end-to-end encrypted.",
    termsAndConditionsStarter_label: "I have read and agree to the <a href=\"https://tutanota.de/#!termsstarter\" target=\"_blank\" data-bind=\"tabindex=\"-1\">general terms and conditions</a> and the <a href=\"https://tutanota.de/#!privacy\" target=\"_blank\" data-bind=\"tabindex=\"-1\">privacy policy</a>.",
    termsAndConditionsFree_label: "I confirm that I will use Tutanota as private user and I have read and agree to the <a href=\"https://tutanota.de/#!termsfree\" target=\"_blank\" data-bind=\"tabindex=\"-1\">general terms and conditions</a> and the <a href=\"https://tutanota.de/#!privacy\" target=\"_blank\" data-bind=\"tabindex=\"-1\">privacy policy</a>.",
    join_action: "Join",
	joinNeutral_msg: "Join to receive your personal verification code via SMS for verifying your mobile phone number.",
	joinRunning_msg: "A SMS is being sent...",
	joinFailure_msg: "Sorry, we could not send the SMS. Please try again later.",
    joinAccountLimitReached_msg: "Sorry, we could not send the SMS. The account limit is reached.",
    verifyDomain_action: "Verify domain",
	verifyDomainNeutral_msg: "Send email to verify domain",
	verifyDomainRunning_msg: "An email is being sent for verifying your domain...",
	verifyDomainMailSent_msg: "A short email has been sent to \"$1\" for verifying that you are the owner of \"$2\".\n\nJust click on the link within the received email and you will be able to finish your Tutanota registration within a few minutes.",
	verifyDomainStaffInformed_msg: "Our sales team has been informed about your interest in Tutanota Starter and and is going to verify your domain \"$2\".\n\nThis manual verification step usually takes a few hours. You will be informed by email to \"$1\" as soon as the verification process is done.",
	codeInputInfo_msg: "The code was sent to $.",
	createAccount_action: "Create account",
	createAccountRunning_msg: "Account is being created...",
	createAccountTooManyAttempts_msg: "Too many wrong attempts. Please try again later.",
    createAccountTooManyAccountsError_msg: "Sorry, but the maximum number of accounts is reached.",
	createAccountInfo_msg: "Depending on your computer's individual performance it may take some minutes to generate your secure keys.",
    createAccountInfoMobile_msg: "On mobile devices it may take several minutes to generate your secure keys. If it takes too long, please use a desktop computer for registration.",
	name_label: "Name",
    nameAdmin_label: "Name of the administrator",
	mobileNumber_label: "Mobile phone number",
	desiredAddress_label: "Desired email address",
	repeatedPassword_label: 'Repeat password',
	registrationCodeInput_label: "Verification code",
	progress_msg: "Progress",
	terms_label: "Confirmation",
	termsAcceptedNeutral_msg: "Please accept the terms & conditions.",
    backTologin_action: "Back to login",

	// feedback
	errorReport_label: "Oh no!",
    errorReportDescription_msg: "An unexpected error occurred. Please tell us what happened and we will fix the problem as soon as possible.",
    screenshot_label: "Attach screenshot",
    feedbackInfo_msg: "The message and your browser identifier are sent encrypted to support@tutao.de.",
    feedbackErrorInfo_msg: "The message, error details and your browser identifier are sent encrypted to support@tutao.de.",
    faq_msg: "If you have a question about Tutanota, please check the <a target=\"_blank\" href=\"https://tutanota.de/#!faq\">FAQ</a> first.",

	// outlook
	tutanotaStarter_label: "Tutanota Starter for Microsoft Outlook",
	version_label: "Version:",
	tutanotaWebClientColon_label: "Tutanota Webapp:",
	tutanotaWebClient_label: "Tutanota Webapp",
	help_label: "Get help:",
	sendLogFile_action: "Send log file via email",
	info_label: "Info",
	changePassword_label: "Change password",
	account_label: "User",
	selectAddress_label: "Please select email address",
	passwordNeutral_msg: "Your Tutanota password.",
	savePassword_label: "Remember",
	savePassword_msg: "Store the password and do not ask me again for it.",
	confidentialDefault_label: "Confidential default",
	confidentialDefault_msg: "Send new messages confidentially by default.",
	noConnection_msg: "You are offline. A connection to Tutanota could not be established.",
	loginAction_msg: "You will only receive secure Tutanota emails after logging in.",
	presharedPasswordAndStrength_msg: "Password strength:",
	confidentiality_label: "Confidentiality",
	confidentialityOffline_msg: "You are offline and this message will not be sent confidentially. Click to send a confidential message.",
	confidentialityDisabled_msg: "This message will not be sent confidentially. Click to send a confidential message.",
	confidentialityEnabled_msg: "This message will be sent confidentially.",
	localMailBegin_msg: "This message has been sent confidentially with <a href=\"http://tutanota.com\">Tutanota</a> to the following recipients:",
	technicalError_msg: "A technical error occured. Please try again later. Inform your administrator if this error occurs again.",
	invalidSwVersion_msg: "Your Tutanota addin has to be updated. When you restart Outlook the new version will automatically be downloaded and installed.",
	accountDeactivated_msg: "Unfortunately, your Tutanota account was deactivated. Please contact your administrator.",
	sending_msg: 'Your message is being encrypted and sent.',
	sendingFailed_msg: 'Could not send the message. Please try again later.',
	savingFailed_msg: 'The message has been sent successfully but could not be stored into your sent messages folder.',
	outlookVersionNotSupported_msg: 'Unfortunately, Tutanota does not support this version of Outlook. Please use Outlook 2010 or Outlook 2013.',
	invalidAttachment_msg: "This email can not be sent via Tutanota because it contains an unsupported attachment.",
	showInAddressBook_alt: "Edit contact",
	testPhaseExpired_msg: "The free testing phase has expired and the sending of confidential emails has been deactivated. Please contact your administrator.",
	autoTransmitPassword_label: "Automatic passwort exchange via text message",
	setMobileNumber_msg: "Please enter mobile phone number.",
	mobileNumberValidFormat_msg: "Format ok.",
	invalidPasswordChannel_msg: "Please enter a valid mobile phone number or a strong password for the following recipient: ",
	passwortChannelColumnHeading_label: "Tutanota",
	passwordChannelColumnInfoInternal_msg: "This message is being encrypted and sent confidentially via Tutanota. All recipients use Tutanota so you do not need to exchange any passwords.",
	passwordChannelColumnInfoExternal_msg: "This message is being encrypted and sent confidentially via Tutanota. Please enter a mobile phone number or an agreed password for each external recipient.",
	passwordChannelColumnInfoMixed_msg: "This message is being encrypted and sent confidentially via Tutanota. Please enter a mobile phone number or an agreed password only for the external recipients listed below.",
	messageNotStored_msg: "A confidential email has been received with Tutanota but could not be stored on your mail server. Would you like to send the log files for analysis to Tutao GmbH?",
	errorNotification_label: "Error notification",
    notificationMailSignature_label:  "Signature",
    notificationMailSignatureNone_msg:  "<none>",
	notificationMailSignature_msg: "This signature will be used for all notification emails to external recipients.",
    notificationMailSignatureSubject_msg: "Confidential email from $1",
    notificationMailSignatureMessage_msg: "<p style=\"font-family:'Calibri',sans-serif\">Hello,</p><p style=\"font-family:'Calibri',sans-serif\">I have sent a confidential email to you. For that I am using <a href='https://tutanota.de/#!info'>Tutanota</a>, the reviewed and certified service from Germany for encrypted emails. You can read this email - and all already exchanged ones - by simply clicking the following link:</p><p style=\"font-family:'Calibri',sans-serif\"><a href='$1'>Show email</a></p><p style=\"font-family:'Calibri',sans-serif\">This email was automatically generated for sending the link. The link stays valid until you receive a new confidential email from me.</p><p style=\"font-family:'Calibri',sans-serif\">Kind regards<br/>$2</p>",
    signatureConfigFailure_msg: "There is no valid email signature configuration for notification emails to external recipients. Would you like to send the notification email without a signature?",
    unsupportedMailFeature_msg: "You have selected voting options or a deferred delivery time. Unfortunately these functions are not yet supported by Tutanota. Would you like to send the email anyway?",
    readOrTransmissionReceiptWithInternals_msg: "You have selected a transmission or read receipt for your email. Unfortunately, these functions are only supported for external recipients. Would you like to send the email anyway?"
};

tutao.tutanota.ctrl.LanguageViewModel.de = {
	// mail
	deleteMail_msg:	"Neue E-Mail verwerfen ohne zu senden?",
	tooBigAttachment_msg: "Die folgenden Dateien konnten nicht angehängt werden, da die Gesamtgröße 25 MB übersteigt: ",
	received_action: "Posteingang",
	receivedMail_alt: "Empfangene E-Mail",
	receivedMails_alt: "Empfangene E-Mails",
	sent_action: "Gesendet",
	sentMail_alt: "Gesendete E-Mail",
	sentMails_alt: "Gesendete E-Mails",
	trash_action: "Papierkorb",
	trashedMail_alt: "Gelöschte E-Mail",
	trashedMails_alt: "Gelöschte E-Mails",
	mailWithAttachment_alt: "E-Mail mit Anhang",
	meNominative_label: "Ich",
	meDativ_label: "Mir",
	meAccusative_label: "Mich",
	from_label: "Von",
	to_label: "An",
	cc_label: "Cc",
	bcc_label: "Bcc",
	ccBcc_label: "B/Cc",
	closedLock_alt: 'Geschlossenes Schloss',
	openedLock_alt: 'Offenes Schloss',
	attachFiles_action: "Dateien anhängen",
	removeAttachment_alt: "Anhang entfernen",
	passwordTransmission_label: "Passwortübertragung",
	atLeastOneMobileNumber_label: "Für jeden externen Empfänger ist mindestens eine deutsche Mobilfunknummer oder ein vereinbartes Passwort notwendig.",
    preSharedPasswordNeeded_label: "Bitte geben sie für jeden externen Empfänger ein vereinbartes Passwort an.",
    autoTransmitPasswordDeactivated_label: "Die Passwortübertragung per SMS wird zur Zeit nicht unterstützt.",
	secureMail_title: 'Die E-Mail wird für alle externen Empfänger verschlüsselt.',
	unsecureMail_title: 'Die E-Mail wird unverschlüsselt an externe Empfänger gesendet.',
	noRecipients_msg: 'Sie müssen mindestens einen Empfänger angeben.',
	invalidRecipients_msg: 'Bitte korrigieren Sie die ungültigen E-Mail-Adressen der Empfänger.',
	noSubject_msg: 'Bitte geben Sie einen Betreff für die E-Mail an.',
	noPasswordChannels_msg: 'Bitte geben Sie eine Mobilfunknummer oder ein vereinbartes Passwort für jeden externen Empfänger an.',
    noPreSharedPassword_msg: 'Bitte geben Sie ein vereinbartes Passwort für jeden externen Empfänger an.',
	invalidPasswordChannels_msg: 'Bitte überprüfen Sie die Mobilfunknummern auf Gültigkeit.',
	maxSizeExceeded_msg: "Die maximale Größe von $ für unsichere Nachrichten an externe Empfänger wurde überschritten.",
	send_action: "Absenden",
	reply_action: "Antworten",
	replyAll_action: "Allen antworten",
	forward_action: "Weiterleiten",
	replyConfidential_action: "Vertraulich antworten",
    export_action: "Exportieren",
    deleteTrash_action: "Leeren",
	by_label: "von",
	date_label: "Datum",
	subject_label: "Betreff",
    confidential_label: "Vertraulich",
	showQuotation_action: "+ Details",
	hideQuotation_action: "- Details",
	legacyNoReplyIe_msg: "Dies ist eine alte Version des Internet Explorer und unterstützt nicht das Antworten auf oder das Exportieren von E-Mails. Falls Sie diese Funktionalität benötigen, aktualisieren Sie Ihren Browser oder verwenden Sie einen der folgenden:",
    legacyNoAttachmentsIeMobile_msg: "Internet Explorer auf Windows Phone unterstützt leider nicht das Herunterladen von Anhängen oder das Anhängen von Dateien an E-Mails. Falls Sie diese Funktionalität benötigen, verwenden Sie bitte einen der folgenden Browser:",
    legacyNoReplyAndroid_msg: "Der Android-Browser unterstützt nicht das Antworten auf E-Mails sowie das Abspeichern von Anhängen. Manche Dateitypen können aber im Browser angezeigt werden. Bitte verwenden Sie andernfalls einen der folgenden Browser:",
    legacyDownloadNotPossible_msg: "Leider unterstützt Safari nicht das Exportieren von E-Mails oder das Abspeichern von Anhängen. Manche Dateitypen können aber im Browser angezeigt werden. Bitte verwenden Sie andernfalls einen der folgenden Browser:",
	clickToSave_label: "Klicken zum speichern",
	confidential_action: "Vertraulich",
	nonConfidential_action: "Nicht vertraulich",
    confidentialStatus_msg: "Diese Nachricht wird Ende-zu-Ende verschlüsselt.",
    confidentialSwitchableStatus_msg: "Diese Nachricht wird Ende-zu-Ende verschlüsselt.",
    nonConfidentialStatus_msg: "Diese Nachricht wird nicht Ende-zu-Ende verschlüsselt.",
	noMails_msg: "Keine E-Mails in dieser Liste.",
	noMail_msg: "Keine E-Mail ausgewählt.",
	addMobileNumber_msg: "Zusätzliche Mobilfunknummer eingeben.",
	setPresharedPassword_action: "Vereinbartes Passwort setzen",
	presharedPassword_label: "Vereinbartes Passwort",
	mobileNumberNotValid_msg: "Format ist nicht gültig.",
	fromAddressBook_label: "Aus Adressbuch: ",
	presharedPasswordNotStrongEnough_msg: "Mindestens eines der eingegebenen Passwörter ist nicht sicher genug. Wollen Sie die E-Mail trotzdem senden?",
    showAttachment_label: "Anhang anzeigen",
    saveDownloadNotPossibleSafariDesktop_msg: "Leider unterstützt Safari nicht das Abspeichern von Anhängen. Manche Dateitypen können aber im Browser durch Klicken auf den obigen Link angezeigt werden. Bitte verwenden Sie andernfalls Mozilla Firefox oder Google Chrome.",
    saveDownloadNotPossibleSafariMobile_msg: "Leider unterstützt Safari nicht das Abspeichern von Anhängen. Manche Dateitypen können aber im Browser durch Klicken auf den obigen Link angezeigt werden. Bitte verwenden Sie andernfalls einen Desktop-Browser.",
    saveDownloadNotPossibleAndroid_msg: "Leider unterstützt der Android-Browser nicht das Abspeichern von Anhängen. Manche Dateitypen können aber im Browser durch Klicken auf den obigen Link angezeigt werden. Bitte installieren Sie andernfalls Google Chrome oder Opera.",
    saveDownloadNotPossibleIe_msg: "Leider unterstützt der mobile Internet Explorer nicht das Abspeichern oder Anzeigen von Anhängen. Bitte verwenden Sie dafür einen Desktop-Browser.",
    addAttachmentNotPossibleIe_msg: "Leider unterstützt der mobile Internet Explorer nicht das Anhängen von Dateien an E-Mails. Bitte verwenden Sie dafür einen Desktop-Browser.",
	downloadAttachmentNotPossible_msg: "Der ausgewählte Anhang kann leider nicht angezeigt werden. Anhänge größer als 7 MB werden auf diesem Gerät zur Zeit nicht unterstützt.",
    removeRecipient_alt: "Empfänger entfernen",
    couldNotAttachFile_msg: "Die Datei konnte leider nicht geladen werden.",
    changeNotificationMailLanguage_msg: "Sprache der Benachrichtigungs-E-Mail:",
    reallySubmitContent_msg: "Wollen Sie die eingegebenen Daten wirklich an eine externe Seite senden?",
    search_title: "Suche",
	loadMoreMails_action: "Weitere E-Mails laden",
    confirmDeleteTrash_msg: "Möchtest du wirklich alle E-Mails aus dem Papierkorb löschen?",
	newMails_msg: "Neue Nachricht in Tutanota eingetroffen.",
    newMailBadge_msg: "1 neue E-Mail empfangen",
    newMailsBadge_msg: "%d neue E-Mails empfangen",
    passwords_label: "Passwörter",
    showPasswordChannelColumn_title: "Passwörter für externe Empfänger eingeben.",
    confidentialMail_alt: "Diese E-Mail wurde Ende-zu-Ende verschlüsselt übertragen.",

    //invitation
    invitationMailSubject_msg: "Sei dabei: Mit Tutanota holen wir uns unsere Privatsphäre zurück!",
    invitationMailBody_msg: "Hallo!<br><br>Ich möchte dich gern zu Tutanota einladen. Mit dem kostenlosen E-Mail-Service können wir ganz einfach Ende-zu-Ende verschlüsselt mailen. So können wir vertraulich miteinander kommunizieren und einen Beitrag gegen die Massenüberwachung im Internet leisten.<br><br>Melde dich einfach hier an:<br><a href=\"https://app.tutanota.de/#register\">https://app.tutanota.de/#register</a><br><br>Ich freue mich auf deine erste verschlüsselte E-Mail.<br><br>Viele Grüße<br>$<br><br>PS: Tutanota verschlüsselt alle unsere Daten automatisch, noch dazu ist es Open Source: <a href=\"https://github.com/tutao/tutanota\">https://github.com/tutao/tutanota</a>",

	// contact
	discardContact_msg: "Neuen Kontakt verwerfen?",
	discardContactChanges_msg: "Änderungen an Kontakt verwerfen?",
	discardContactChangesFor_msg: "Änderungen an Kontakt \"$\" verwerfen?",
	deleteContact_msg: "Möchten Sie den Kontakt tatsächlich löschen?",
	private_label: "Privat",
	mobile_label: "Mobil",
	fax_label: "Fax",
	work_label: "Arbeit",
	other_label: "Anderes",
	custom_label: "Eigenes",
	twitter_label: "Twitter",
	facebook_label: "Facebook",
	xing_label: "Xing",
	linkedin_label: "Linked in",
	email_label: "E-Mail",
	phone_label: "Telefon",
	address_label: "Adresse",
	social_label: "Soziale Netzwerke",
	comment_label: "Kommentar",
	birthday_alt: "Geburtstag",
	contactImage_alt: "Foto dieses Kontakts",
	removePhoneNumber_alt: "Telefonnummer löschen",
	removeMailAddress_alt: "E-Mail-Adresse löschen",
	removeAddress_alt: "Adresse löschen",
	removeSocial_alt: "Link auf dieses Profil löschen",
	sendMail_alt: "E-Mail an diese Adresse senden",
	callNumber_alt: "Diese Telefonnummer anrufen",
	showAddress_alt: "Diese Adresse in Google Maps anzeigen",
	openSocial_alt: "Profil des Nutzers öffnen",
	firstName_placeholder: "Vorname",
	lastName_placeholder: "Nachname",
	birthdayWithFormat_placeholder: "Geburtstag (tt.mm.jjjj)",
	company_placeholder: "Firma",
	title_placeholder: "Titel",
	noContacts_msg: "Keine Kontakte in der Liste.",
	noContact_msg: "Kein Kontakt ausgewählt.",
	passwordsHeading_label: "E-Mail-Passwörter:",
	presharedPasswordHeading_label: "Vereinbart:",
	autoTransmitPasswordHeading_label: "SMS:",
	showPassword_alt: "Button gedrückt halten, um das Passwort anzuzeigen.",
	
	// settings
	accountSettings_action: "Account",
	securitySettings_action: "Sicherheit",
	changePasswordSettings_action: "Passwort ändern",
	adminUserList_action: "Benutzerverwaltung",
    adminDeleteAccount_action: "Account löschen",
	adminUserAdd_action: "Benutzer hinzufügen",
    adminPremiumFeatures_action: "Erweiterungen",
    adminMessages_action: "Anzeigetexte",
	action_label: "Aktion",
	edit_label: "Bearbeiten",
	editUser_label: "Benutzer bearbeiten",
	save_msg: "Die Daten werden gespeichert ...",
	saved_msg: "Die Daten wurden erfolgreich gespeichert.",
	state_label: "Zustand",
	create_action: "Hinzufügen",
	createActionSuccess_msg: "Alle Accounts wurden erfolgreich angelegt.",
    createActionFailed_msg: "Ein Account konnte nicht angelegt werden. Bitte versuchen Sie es später erneut.",
    createActionStatus_msg: "Accounts werden angelegt... Es sind ${index} von ${count} erstellt.",
	import_action: "Importieren",
	importCsv_label: "CSV-Daten importieren",
	importCsvInvalid_msg: "Die CSV-Daten sind ungültig (Zeile $).",
    successfullyCreatedUsers_msg: "Die folgenden Benutzer wurden erfolgreich angelegt. Bitte notieren Sie sich die Passwörter gut und geben Sie sie an die Benutzer weiter.",
    deleted_label: "Gelöscht",
    created_label: "Erstellt",
    addinInfoText_msg: "Hier können Sie das Outlook-Addin für Tutanota Starter herunterladen. Neue Versionen werden automatisch beim Starten von Outlook installiert.",
    promotionCodeEnterNeutral_msg:"Bitte geben Sie hier Ihren Freischaltcode ein, um die Speichererweiterung zu aktivieren",
    promotionCodeEnterWrongFormat_msg: "Ungültiges Format.",
    promotionCodeEnterValidFormat_msg: "Format gültig.",
    promotionCodeInvalid_msg: "Der eingegebene Code ist ungültig.",
	promotionCodeSuccess_msg: "Erweiterung wurde erfolgreich aktiviert.",
    storageCapacity5GB_label: "5GB Speicherkapazität",
    storageCapacity_label: "Speicherkapazität",
    activate_action:"Aktivieren",
    externalWelcomeMessage_label: "Willkommens-Nachricht",
    externalWelcomeMessageInfo_msg: "Diese Nachricht wird externen Empfängern aller Benutzer in der Menüleiste von Tutanota angezeigt. Hier können Sie z.B. den Namen Ihres Unternehmens eintragen.",
    externalWelcomeMessagePreview_label: "Vorschau",
    externalWelcomeMessagePreviewInfo_msg: "So sehen externe Empfänger die Willkommensnachricht.",
    externalWelcomeMessageUpdated_msg: "Nachricht wurde aktualisiert.",
    externalWelcomeMessageFree_msg: "Diese Variante von Tutanota ist ein Service für Privatkunden.",
    storageCapacityNoLimit_label: "unbegrenzt",

	// account settings
	accountType_label: "Account-Typ",
	mailName_label: "Absendername",
	mailNameInfo_msg: "Dieser Name wird Empfängern Ihrer E-Mails angezeigt. Sie können ihn in der Benutzerverwaltung ändern.",
	
	// security settings
	lastSuccessfulLogin_label: "Letzter erfolgreicher Login",
	lastSuccessfulLoginInfo_msg: "Der Zeitpunkt des letzten erfolgreichen Logins vor dem aktuellen Login.",
	failedLogins_label: "Fehlgeschlagene Logins",
	failedLoginsInfo_msg: "Die Anzahl fehlgeschlagener Login-Versuche seit dem letzten erfolgreichen Login.",
	
	// change password
	oldPassword_label: "Altes Passwort",
	oldPasswordNeutral_msg: "Bitte altes Passwort eingeben.",
	oldPasswordInvalid_msg: "Passwort nicht korrekt.",
	newPassword_label: "Neues Passwort",
	securePasswords_link: "http://de.wikipedia.org/wiki/Passwortsicherheit#Wahl_sicherer_Passw.C3.B6rter",
	password1Neutral_msg: "Bitte ein Passwort eingeben.",
	password1InvalidSame_msg: "Neues und altes Passwort sind identisch.",
	password1InvalidUnsecure_msg: "Das Passwort ist nicht sicher genug.",
    password1InvalidTooShort_msg: "Das Passwort ist zu kurz.",
	password2Neutral_msg: "Bitte Passwort wiederholen.",
	password2Invalid_msg: "Passwörter sind nicht identisch.",
	verificationCode_msg: "Der Bestätigungscode wird Ihnen per SMS zugesendet.",
	code_label: "Bestätigungscode",
	pwChangeValid_msg: "Passwort wurde geändert.",
	pwChangeInvalidTooManyVerifyAttempts_msg: "Anzahl erlaubter Versuche überschritten. Bitte versuchen Sie es es später erneut.",
	pwChangeInvalidTooManyChangeAttempts_msg: "Das Passwort wurde zu häufig geändert. Bitte versuchen Sie es es später erneut.",
	pwChangeButtonSendCode_action: "Code senden",
	pwChangeButtonChangePw_action: "Passwort ändern",
	serverNotReachable_msg: "Der Server konnte nicht erreicht werden, sie sind offline. Bitte versuchen Sie es es später erneut.",
    outdatedClient_msg: "Bitte aktualisieren Sie Tutanota. Die aktuell installierte Version ist zu alt und wird nicht länger unterstützt.",
    unknownError_msg: "Es ist ein unerwarteter Fehler aufgetreten. Bitte versuchen Sie es später erneut.",
    passwordNotChanged_msg: "Das Passwort ist nicht geändert.",
    passwordResetFailed_msg: "Es ist ein Fehler aufgetreten. Das Passwort wurde nicht geändert.",
    notePassword_msg: "Bitte notieren Sie sich das Passwort gut und geben Sie es an den Benutzer weiter.",
    changePasswordNotSupported_msg: "Aus Sicherheitsgründen wird die Passwortänderung auf mobilen Geräten nicht unterstützt.",

    // delete account
    deleteAccountReason_label: "Warum?",
    deleteAccountReasonInfo_msg: "Optional: Wir würden uns freuen, wenn du uns einen kurzen Hinweis gibst, warum du deinen Account löschen möchtest, damit wir Tutanota verbessern können.",
    deleteAccountInfo_msg: "Der gesamte Account wird gelöscht.",
    deleteAccountConfirm_msg: "Wollen Sie Ihren Account wirklich löschen?",
    deleteAccountWait_msg: "Account wird gelöscht...",
    deleteAccountDeleted_msg: "Dein Account ist jetzt gelöscht.",

	// general
	emptyString_msg: "\u2008",
	save_action: "Speichern",
	dismiss_action: "Verwerfen",
	cancel_action: "Abbrechen",
	edit_action: "Ändern",
	delete_action: "Löschen",
	undelete_action: "Wiederherstellen",
    finalDelete_action: "Löschen",
	print_action: "Drucken",
	back_action: "Zurück",
	ok_action: "OK",
    newMail_action: "Neue E-Mail",
	monthNames_label: ["Jan", "Feb", "Mär", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"],
	weekDays_label: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
	yesterday_label: "gestern",
	busy_alt: "Bitte warten...",
	close_alt: "Schließen",
	german_alt: "Deutsch",
	english_alt: "English",
	check_msg: "Überprüfe...",
	add_action: "Hinzufügen",
	remove_action: "Entfernen",
	notFound404_msg: "Leider konnte die von Ihnen aufgerufene Seite nicht gefunden werden. Bitte prüfen Sie die URL nach Fehlern und aktualisieren die aktuelle Seite.",
    loading_msg: "Lade...",
    show_action: "Öffne",
    applicationUpdate_label: "Tutanota wird geladen...",
    leavePageConfirmation_msg: "Wollen Sie Tutanota wirklich schließen?",
    loadMore_action: "Weitere laden",
    newContact_action: "Neuer Kontakt",
    password_label: 'Passwort',
    passwordEnterNeutral_msg: "Bitte gib dein Passwort als Bestätigung ein.",
    passwordWrongInvalid_msg: "Das Passwort ist falsch.",
    passwordValid_msg: "Passwort ok.",


    // code verification
	codeNeutralEnterCode_msg: "Bitte den Bestätigungscode eingeben.",
	codeValid_msg: "Code-Format ok.",
	codeInvalid_msg: "Der Code ist nicht korrekt, bitte überprüfen Sie ihn erneut.",

	// external login
	receiveMsg_label: "Nachricht empfangen",
	invalidLink_msg: "Leider ist dieser Link ungültig.",
	expiredLink_msg: "Leider ist dieser Link nicht mehr gültig. Sie sollten eine neue Benachrichtigungs-E-Mail mit einem aktuellen Link von diesem Absender bekommen haben. Vorhergehende Links werden aus Sicherheitsgründen deaktiviert.",
	sendSms_action: "Sende SMS",
	smsError_msg: "Die SMS konnte nicht gesendet werden.",
	smsSent_msg: "Die SMS sollte innerhalb von 60s ankommen.",
	smsResent_msg: "Wenn die SMS nicht angekommen ist, dann können Sie diese nun erneut senden.",
	smsSentOften_msg: "Es wurden zu viele SMS versendet. Fragen Sie den Sender der Nachricht, ob er Ihnen diese erneut zukommen lassen kann.",
	invalidPassword_msg: "Das Passwort ist leider ungültig.",
	showMail_action: "Mailbox anzeigen",
	chooseNumber_msg: "Bitte klicken Sie auf einen der \"Sende SMS\"-Buttons. Das Tutanota-Passwort für Ihre Mailbox wird an die angegebene Mobilfunknummer versendet (maximal drei SMS).",
	clickNumber_msg: "Bitte klicken Sie auf den \"Sende SMS\"-Button. Das Tutanota-Passwort für Ihre Mailbox wird an die angegebene Mobilfunknummer versendet (maximal drei SMS).",
	storePassword_action: "Passwort speichern",
	enterPresharedPassword_msg: "Bitte geben Sie das mit dem Absender vereinbarte Passwort ein.",
	sendingSms_msg: "SMS wird gesendet...",
	onlyPrivateComputer_msg: "Wählen Sie diese Option nur, wenn Sie ein privates Gerät verwenden.",
	loadingMail_msg: "Lade Mailbox...",
	enterSmsPassword_msg: "Bitte geben Sie hier das per SMS übertragene Passwort ein oder klicken Sie auf den Link in der SMS.",

	// login
	welcome_msg: "Login",
	afterRegistration_msg: "Dein Account ist erstellt. Logge dich jetzt ein!",
	loginFailedOften_msg: "Es sind zu viele Login-Versuche fehlgeschlagen. Bitte versuchen Sie es später erneut.",
	loginFailed_msg: "Ungültige E-Mail-Adresse oder Passwort. Bitte versuchen Sie es erneut.",
	login_action: "Anmelden",
	login_msg: 'Sie werden eingeloggt.',
	mailAddress_label: "E-Mail-Adresse",
    socialMedia_label: "Folge uns für Updates:",

    appInfoAndroidUrl_action: "https://play.google.com/store/apps/details?id=de.tutao.tutanota",
    appInfoIosUrl_action: "https://itunes.apple.com/app/tutanota/id922429609?ls=1&mt=8",
    appInfoAndroidImage_action: "graphics/android_de.png",
    appInfoIosImage_action: "graphics/ios_de.png",
    appInfoAndroidImageAlt_alt: "Android app bei Google Play",
    appInfoIosImageAlt_alt: "iOS app im Apple store",

	// header
	logo_alt: "Tutanota-Logo",
	featureNotAvailable_msg: "Diese Funktion wird in 2014 verfügbar sein!",
	emails_label: "E-Mails",
	emails_alt: "E-Mails",
	newMail_alt: "Neue E-Mail",
	contacts_label: "Kontakte",
	contacts_alt: "Kontakte",
	newContact_alt: "Neuer Kontakt",
	newFolder_alt: "Neuer Ordner",
	files_alt: "Dateien",
	files_label: "Dateien",
	calendar_label: "Kalender",
	calendar_alt: "Kalender",
	tasks_label: "Aufgaben",
	tasks_alt: "Aufgaben",
	feedback_label: "Feedback",
	feedback_alt: "Feedback",
	logout_label: "Abmelden",
	logout_alt: "Abmelden",
    dev_label: "Developer",
	settings_label: "Einstellungen",
	settings_alt: "Einstellungen",
    register_label: "Registrieren",
    register_alt: "Registrieren",
    invite_label: "Einladen",
    invite_alt: "Einladen",
    more_label: "Mehr",
    dots_label: "...",
    folderTitle_label: "Ordner",

    //admin
    logs_label: "logs",
    db_label: "db",
    monitor_label: "monitor",
    config_label: "config",
    customers_label: "customers",

	// not supported
	for_label: "für",
	oldBrowser_msg: "Oh, das tut uns leid. Sie verwenden eine veraltete Version Ihres Browsers. Bitte nutzen Sie die aktuelle Version einer der folgenden Browser:",
	unsupportedBrowser_msg: "Oh! Das tut uns leid. Sie verwenden einen nicht unterstützten Browser. Bitte nutzen Sie einen der folgenden Browser:",
	browserNoKeygen_msg: "Lieber Interessent von Tutanota, während der Registrierung werden Schlüssel erzeugt. Die Erzeugung dieser Schlüssel benötigt mehr Rechenleistung als Ihr momentan verwendetes Gerät bereitstellt. Daher registrieren Sie sich bitte am besten auf einem Desktoprechner oder Laptop und verwenden dabei einen der folgenden Browser:",
	thanks_msg: "Vielen Dank für Ihr Verständnis.\nIhr Team von Tutanota",

	// registration
    regLinkInvalid_msg: "Es tut uns leid, dieser Registrierungslink ist nicht gültig.",
    regDisabledFree_msg: "Die Anzahl an Registrierungen für Tutanota Free ist limitiert und im Moment leider nicht möglich. Bitte folge uns hier, um eine Benachrichtigung zu erhalten sobald weitere Registrierungen möglich sind:",
    regDisabledStarter_msg: "Die Anzahl an Registrierungen für Tutanota Starter ist limitiert und im Moment leider nicht möglich. Bitte melden Sie sich hier an, um eine Benachrichtigung zu erhalten sobald weitere Registrierungen möglich sind:",
	claim_label: "Tutanota - einfach. sicher. mailen.",
	registrationHeadline_msg: "Tutanota Registrierung",
    registrationHeadlineBeta_msg: "Tutanota Beta Registrierung",
    registrationSubHeadline1_msg: "Domain-Prüfung (Schritt 1 von 2)",
    registrationSubHeadline2_msg: "Registrierungsdaten eingeben (Schritt 2 von 2)",
	company_label: "Firma",
	domain_label: "Domain",
    currentMailAddress_label: "Ihre E-Mail-Adresse",
    currentMailAddressAdmin_label: "E-Mail-Adresse des Administrators",
	companyNameNeutral_msg: "Bitte Firmennamen eingeben.",
	companyNameValid_msg: "Firmenname ok.",
	verifyingCode_msg: "Der Code wird überprüft. Bitte haben Sie einen Moment Geduld.",
	sendingSms_alt: "SMS wird gesendet. Bitte haben Sie einen Moment Geduld.",
	creatingAccount_alt: "Ihr Account wird angelegt. Bitte haben Sie einen Moment Geduld.",
    domainInfo_msg: "Hiermit bestätigen Sie, dass Sie diese Domain verwalten dürfen.",
	loginNameInfo_msg: "Ihr Vor- und Nachname.",
    loginNameInfoAdmin_msg: "Optional: Der Name des Benutzers.",
    loginNameInfoFree_msg: "Optional: Dieser Name wird Empfängern Ihrer E-Mails angezeigt.",
	mobileNumberInfo_msg: "Bitte mit <a href=\"https://de.wikipedia.org/wiki/L%C3%A4ndervorwahlliste_sortiert_nach_L%C3%A4ndern\" target=\"_blank\">Ländervorwahl</a> eingeben, z.B. +4917012345678. Ihre Mobilfunknummer wird zur Autorisierung benötigt, wenn Sie Ihr Passwort ändern möchten.",
	mobileNumberNeutral_msg: "Bitte Mobilfunknummer eingeben.",
	mobileNumberValid_msg: "Mobilfunknummer ok.",
	mobileNumberInvalid_msg: "Ungültige Mobilfunknummer.",
    mobileNumberNoCountryCode_msg: "Ländervorwahl fehlt, z.B. +49 für Deutschland.",
    currentMailAddressInfo_msg: "Diese E-Mail-Adresse wird genutzt, um zu prüfen, dass Ihnen die Domain gehört oder Sie diese verwalten dürfen.\nTipp: Benutzen Sie eine der Adressen postmaster@<Ihre_Domain> oder hostmaster@<Ihre_Domain>, um die Registrierung sofort fortzusetzen (automatische Prüfung). Eine manuelle Prüfung wird für alle anderen Adressen durchgeführt und kann bis zu einem Werktag benötigen.",
	mailAddressInfo_msg: "Dies wird Ihre neue E-Mail-Adresse. Es werden mindestens vier Buchstaben benötigt.",
    mailAddressInfoBusiness_msg: "Ihre vorhandene E-Mail-Adresse.",
    mailAddressInfoAdmin_msg: "Die E-Mail-Adresse des Benutzers.",
	mailAddressNeutral_msg: "Bitte E-Mail-Adresse eingeben.",
    mailAddressValid_msg: "Die E-Mail-Adresse ist gültig.",
	mailAddressInvalid_msg: "Ungültige E-Mail-Adresse.",
	mailAddressAvailable_msg: "E-Mail-Adresse ist verfügbar.",
	mailAddressNA_msg: "E-Mail-Adresse ist bereits vergeben.",
    mailAddressDelay_msg: "Zu viele Anfragen, bitte später erneut versuchen.",
	mailAddressBusy_msg: "E-Mail-Adresse wird überprüft...",
	pwStrength_title: "Zeigt den Sicherheitsgrad des verwendeten Passworts an",
	goodPassphrase_action: "Wie finde ich ein gutes Passwort?",
    passwordImportance_msg: "Bitte bewahren Sie dieses Passwort an einem sicheren Ort auf. Wir können das Passwort nicht wiederherstellen oder den Account zurücksetzen, da Ihre Daten Ende-zu-Ende verschlüsselt gespeichert werden.",
	termsAndConditionsStarter_label: "Ich habe die <a href=\"https://tutanota.de/#!termsstarter\" target=\"_blank\" data-bind=\"tabindex=\"-1\">Allgemeinen Geschäftsbedingungen</a> und die <a href=\"https://tutanota.de/#!privacy\" target=\"_blank\" data-bind=\"tabindex=\"-1\">Datenschutzerklärung</a> gelesen und erkenne diese an.",
    termsAndConditionsFree_label: "Ich bestätige, dass ich Tutanota als Privatnutzer verwenden werde, und habe die <a href=\"https://tutanota.de/#!termsfree\" target=\"_blank\" data-bind=\"tabindex=\"-1\">Allgemeinen Geschäftsbedingungen</a> und die <a href=\"https://tutanota.de/#!privacy\" target=\"_blank\" data-bind=\"tabindex=\"-1\">Datenschutzerklärung</a> gelesen und erkenne diese an.",
	join_action: "Fortfahren",
	joinNeutral_msg: "Sie erhalten anschließend per SMS einen Bestätigungscode für die angegebene Mobilfunknummer.",
	joinRunning_msg: "Die SMS wird gesendet...",
	joinFailure_msg: "Leider konnte die SMS nicht gesendet werden. Bitte versuchen Sie es später erneut.",
    joinAccountLimitReached_msg: "Leider konnte die SMS nicht gesendet werden. Die maximale Anzahl Accounts ist erreicht.",
    verifyDomain_action: "Domain prüfen",
    verifyDomainNeutral_msg: "E-Mail zur Prüfung der Domain zusenden.",
    verifyDomainRunning_msg: "Die E-Mail zur Prüfung Ihrer Domain wird Ihnen zugesendet...",
    verifyDomainMailSent_msg: "Eine kurze E-Mail wurde an \"$1\" gesendet, um zu prüfen, dass Sie der Besitzer der Domain \"$2\" sind.\n\nDie E-Mail enthält einen Bestätigungslink. Klicken Sie auf diesen, um die Registrierung innerhalb von wenigen Minuten abzuschließen.",
    verifyDomainStaffInformed_msg: "Unser Vertriebsteam wurde über Ihr Interesse informiert und wird Ihre Domain \"$2\" innerhalb der nächsten Stunden prüfen.\n\nSobald die Prüfung abgeschlossen ist, werden wir Sie umgehend per E-Mail an \"$1\" informieren.",
	codeInputInfo_msg: "Der Code wurde gesendet an $.",
	createAccount_action: "Account anlegen",
	createAccountRunning_msg: "Account wird erstellt...",
	createAccountTooManyAttempts_msg: "Zu viele falsche Versuche. Bitte versuchen Sie es später erneut.",
    createAccountTooManyAccountsError_msg: "Leider ist die maximale Anzahl Accounts erreicht.",
	createAccountInfo_msg: "Abhängig von der Geschwindigkeit Ihres Computers kann es einige Minuten dauern, bis Ihre sicheren Schlüssel erzeugt werden.",
    createAccountInfoMobile_msg: "Auf mobilen Geräten kann es mehrere Minuten dauern bis Ihre sicheren Schlüssel erzeugt sind. Falls es Ihnen zu lange dauert, bitten wir Sie für die Registrierung einen Desktoprechner zu verwenden.",
	name_label: "Name",
    nameAdmin_label: "Name des Administrators",
	mobileNumber_label: "Mobilfunknummer",
	desiredAddress_label: "Gewünschte E-Mail-Adresse",
	repeatedPassword_label: 'Passwort wiederholen',
	registrationCodeInput_label: "Bestätigungscode",
	progress_msg: "Fortschritt",
	terms_label: "Bestätigung",
	termsAcceptedNeutral_msg: "Bitte akzeptieren Sie die AGB.",
    backTologin_action: "Abbrechen",

	// feedback
	errorReport_label: "Oh nein!",
    errorReportDescription_msg: "Ein unerwarteter Fehler ist aufgetreten. Bitte beschreiben Sie die von Ihnen ausgeführten Schritte und wir werden das Problem so schnell wie möglich beheben.",
	screenshot_label: "Screenshot mitsenden",
    feedbackInfo_msg: "Die Nachricht wird zusammen mit der Browser-Kennung verschlüsselt an support@tutao.de gesendet.",
    feedbackErrorInfo_msg: "Die Nachricht wird zusammen mit der Browser-Kennung und Fehlerdetails verschlüsselt an support@tutao.de gesendet.",
    faq_msg: "Wenn du eine Frage zu Tutanota hast, schau doch bitte zuerst in den <a target=\"_blank\" href=\"https://tutanota.de/#!faq\">FAQ</a> nach.",

	// outlook
	tutanotaStarter_label: "Tutanota Starter für Microsoft Outlook",
	version_label: "Version:",
	tutanotaWebClientColon_label: "Tutanota Webapp:",
	tutanotaWebClient_label: "Tutanota Webapp",
	help_label: "Hilfe erhalten Sie unter:",
	sendLogFile_action: "Log-Datei per E-Mail senden",
	info_label: "Info",
	changePassword_label: "Passwort ändern",
	account_label: "Benutzer",
	selectAddress_label: "Bitte E-Mail-Adresse auswählen",
	passwordNeutral_msg: "Ihr Tutanota-Passwort.",
	savePassword_label: "Speichern",
	savePassword_msg: "Das Passwort dauerhaft speichern und nicht erneut danach fragen.",
	confidentialDefault_label: "Vertraulich als Standard",
	confidentialDefault_msg: "Neue E-Mails werden standardmäßig vertraulich versendet.",
	noConnection_msg: "Sie sind offline: Es konnte keine Verbindung zu Tutanota hergestellt werden.",
	loginAction_msg: "Nach dem Login können Sie sichere Nachrichten versenden und empfangen.",
	presharedPasswordAndStrength_msg: "Passwortstärke:",
	confidentiality_label: "Vertraulichkeit",
	confidentialityOffline_msg: "Sie sind offline und diese Nachricht wird nicht vertraulich versendet. Klicken Sie, um die Nachricht vertraulich zu senden.",
	confidentialityDisabled_msg: "Diese Nachricht wird nicht vertraulich versendet. Klicken Sie, um die Nachricht vertraulich zu senden.",
	confidentialityEnabled_msg: "Diese Nachricht wird vertraulich versendet.",
	localMailBegin_msg: "Diese Nachricht wurde mit <a href=\"http://tutanota.de\">Tutanota</a> sicher an folgende Empfänger übertragen:",
	technicalError_msg: "Es ist ein technischer Fehler aufgetreten. Bitte versuchen Sie es später noch einmal. Wenden Sie sich an Ihren Administrator, falls der Fehler erneut auftreten sollte.",
	invalidSwVersion_msg: "Ihr Tutanota-Addin muss aktualisiert werden. Wenn Sie Outlook neu starten wird die neue Version automatisch heruntergeladen und installiert.",
	accountDeactivated_msg: "Ihr Tutanota-Account wurde leider deaktiviert. Bitte wenden Sie sich an Ihren Administrator.",
	sending_msg: 'Ihre Nachricht wird verschlüsselt und gesendet.',
	sendingFailed_msg: 'Die Nachricht konnte nicht gesendet werden. Bitte versuchen Sie es später noch einmal.',
	savingFailed_msg: 'Die Nachricht wurde erfolgreich versendet, konnte allerdings nicht in Ihrem Ordner für gesendete Nachrichten gespeichert werden.',
	outlookVersionNotSupported_msg: 'Diese Outlook-Version wird leider nicht von Tutanota unterstützt. Bitte verwenden Sie Outlook 2010 oder Outlook 2013.',
	invalidAttachment_msg: "Diese E-Mail kann leider nicht mit Tutanota gesendet werden, da sie einen nicht unterstützten Anhang enthält.",
	showInAddressBook_alt: "Kontakt bearbeiten",
	testPhaseExpired_msg: "Die kostenfreie Testphase ist abgelaufen, daher ist das Senden von vertraulichen E-Mails deaktiviert worden. Bitte wenden Sie sich an Ihren Administrator.",
	autoTransmitPassword_label: "Automatisches Passwort per SMS",
	setMobileNumber_msg: "Bitte Mobilfunknummer eingeben.",
	mobileNumberValidFormat_msg: "Format ok.",
	invalidPasswordChannel_msg: "Bitte geben Sie eine gültige Mobilfunknummer oder ein ausreichend starkes Passwort für den folgenden Empfänger an: ",
	passwortChannelColumnHeading_label: "Tutanota",
	passwordChannelColumnInfoInternal_msg: "Diese Nachricht wird mit Tutanota verschlüsselt und vertraulich versendet. Da alle Empfänger bei Tutanota registriert sind, ist ein Passwortaustausch nicht notwendig.",
    passwordChannelColumnInfoExternal_msg: "Diese Nachricht wird mit Tutanota verschlüsselt und vertraulich versendet. Bitte geben Sie für jeden externen (nicht bei Tutanota registrierten) Empfänger eine Mobilfunknummer oder ein vereinbartes Passwort an.",
    passwordChannelColumnInfoMixed_msg: "Diese Nachricht wird mit Tutanota verschlüsselt und vertraulich versendet. Bitte geben Sie nur für die unten aufgelisteten externen (nicht bei Tutanota registrierten) Empfänger eine Mobilfunknummer oder ein vereinbartes Passwort an.",
	messageNotStored_msg: "Eine mit Tutanota vertraulich empfangene E-Mail konnte nicht auf Ihrem Mail-Server abgespeichert werden. Wollen Sie die Log-Dateien zur Analyse an die Tutao GmbH senden?",
	errorNotification_label: "Fehlerbenachrichtigung",
    notificationMailSignature_label:  "Signatur",
    notificationMailSignatureNone_msg:  "<keine>",
    notificationMailSignature_msg: "Diese Signatur wird für Benachrichtigungs-E-Mails an externe Empfänger verwendet.",
    notificationMailSignatureSubject_msg: "Vertrauliche Nachricht von $1",
    notificationMailSignatureMessage_msg: "<p style=\"font-family:'Calibri',sans-serif\">Guten Tag,</p><p style=\"font-family:'Calibri',sans-serif\">ich habe Ihnen gerade eine vertrauliche Nachricht gesendet. Daf&uuml;r benutze ich <a href='https://tutanota.de/#!info'>Tutanota</a>, den gepr&uuml;ften und zertifizierten Service aus Deutschland f&uuml;r verschl&uuml;sselte E-Mails. Diese und alle bisher ausgetauschten Nachrichten k&ouml;nnen Sie ganz einfach &uuml;ber den folgenden Link abrufen:</p><p style=\"font-family:'Calibri',sans-serif\"><a href='$1'>Nachricht anzeigen</a></p><p style=\"font-family:'Calibri',sans-serif\">Diese E-Mail wurde für die &Uuml;bermittlung des Links automatisch erzeugt. Der Link bleibt g&uuml;ltig, bis ich Ihnen eine neue vertrauliche Nachricht sende.</p><p style=\"font-family:'Calibri',sans-serif\">Mit freundlichen Gr&uuml;&szlig;en<br/>$2</p>",
    signatureConfigFailure_msg: "Es ist keine gültige E-Mail-Signatur für die Benachrichtigungs-E-Mails an externe Empfänger konfiguriert. Wollen Sie die Benachrichtigungs-E-Mail ohne Signatur senden?",
    unsupportedMailFeature_msg: "Sie haben Abstimmungsschaltflächen oder eine verzögerte Übermittlung der E-Mail ausgewählt. Diese Funktionen werden von Tutanota leider noch nicht unterstützt. Wollen Sie die E-Mail trotzdem senden?",
    readOrTransmissionReceiptWithInternals_msg: "Sie haben eine Übermittlungs- oder Lesebestätigung ausgewählt. Diese Funktionen sind leider nur für externe Empfänger verfügbar. Wollen Sie die E-Mail trotzdem senden?"
};

