import { createEcmaScriptPlugin, type GeneratedFile, type Schema, runNodeJs } from "@bufbuild/protoplugin"
import { type DescFile } from "@bufbuild/protobuf"

const plugin = createEcmaScriptPlugin({
	name: "protoc-gen-capnweb",
	version: "v1",
	generateTs(schema: Schema) {
		for (const file of schema.files) {
			if (file.services.length === 0) continue

			const f = schema.generateFile(`${file.name}_capnweb.ts`)
			f.preamble(file)
			f.print(`// Generate an Adapter for <a href="https://github.com/cloudflare/capnweb">Cap'n Web</a>.`)
			f.print()

			generateServices(file, f)
		}
	},
})

function generateServices(file: DescFile, f: GeneratedFile) {
	for (const service of file.services) {
		f.print(f.export("interface", service.name), " {")

		for (const method of service.methods) {
			// Input TS shapes (method parameter and return types generated by buf.build/bufbuild/es)
			const inputShape = f.importShape(method.input)
			const outputShape = f.importShape(method.output)

			f.print("  ", method.name, "(request: ", inputShape, "): Promise<", outputShape, ">;")
		}

		f.print("}")
		f.print()
	}
}

runNodeJs(plugin)
