[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
tuta-sdk = { path = "../sdk" }
reqwest = "0.12.7"
tokio = { version = "1.40.0", features = ["full"] }
async-trait = "0.1.80"
base64 = "0.22.1"