MIME-Version: 1.0
Content-Type: multipart/mixed;
 boundary="------------050706070100080203090004"

This is a multi-part message in MIME format.
--------------050706070100080203090004
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

Attachment Test

--------------050706070100080203090004
Content-Type: text/plain;
 name="=?UTF-8?B?YXR0YWNobWVudC7DpMO2w7w=?="
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename*=UTF-8''%61%74%74%61%63%68%6D%65%6E%74%2E%C3%A4%C3%B6%C3%BC

VGVzdAo=
--------------050706070100080203090004--
