Content-Type: text/plain; charset="iso-8859-15"
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
MIME-Version: 1.0
X-Mailer: JaM - Just A Mailer
Subject: Testnachricht
Return-Path: <joern@zyn.de>
Date: Wed, 21 Dec 2005 22:02:44 +0100
To: joern@zyn.de
From: =?ISO-8859-15?Q?J=F6rn?= Reder <joern@zyn.de>

=0A=
Hallo,=0A=
=0A=
das ist eine Testnachricht mit 8 Bit S=F6nderz=E4ichen, und obendrein noch=
=20=0A=
quoted-printable kodiert.=0A=
=0A=
Gr=FC=DFe,=0A=
=0A=
J=F6rn=0A=

--=20=0A=
 .''`.  J=F6rn Reder <joern@zyn.de>=0A=
: :' :  http://www.exit1.org/ http://www.zyn.de/=0A=
`. `'=0A=
  `-    Debian GNU/Linux -- The power of freedom=0A=
