Return-Path: <s.rahtz@elsevier.co.uk>
To: Eryq <eryq@rhine.stx.com>
From: s.rahtz@elsevier.co.uk (Sebastian Rahtz)
Subject: Re: HELP! Problems installing PSNFSS, and other querys
Date: Wed, 15 Feb 1995 09:38:18

try reading the LaTeX Companion for more details

ignore the checksum error in lucida.dtx. i'll fix it

sebastian
Sebastian Rahtz                              s.rahtz@elsevier.co.uk
Production Methods Group                     +44 1865 843662
Elsevier Science Ltd
Kidlington
Oxford, UK

