Content-type: text/plain
Subject: Here's my UU'ed sig!

Well, I don't know much about how these things are output, 
so here goes... first off, my .sig file:

begin 644 .signature
M("!?7U\@(%\@7R!?("`@7R`@7U]?(%\@("!%<GEQ("AE<GEQ0'IE96=E92YC
M;VTI"B`O(%\@7'P@)U]\('P@?"!\+R!?("<@+R`@:'1T<#HO+W=W=RYE;G1E
M<F%C="YC;VTO?F5R>7$*?"`@7U\O?"!\('P@?%]\('P@?%]\('P@("`*(%Q?
M7U]\?%]\("!<7U\L('Q<7U\L('Q?7U\O7"`@5FES:70@4U1214545TE312P@
M0VAI8V%G;R=S(&YE=W-P87!E<B!B>2\*("`@("`@("`@("!\7U]?+R`@("!\
M7U]?7U]?+R!O9B!T:&4@:&]M96QE<W,Z(&AT='`Z+R]W=W<N<W1R965T=VES
&92YO<F<*
end

And now, a little .gif icon:

begin 644 
M1TE&.#EA%``6`,(``/___\S__YF9F3,S,P```````````````"'^3E1H:7,@
M87)T(&ES(&EN('1H92!P=6)L:6,@9&]M86EN+B!+979I;B!(=6=H97,L(&ME
M=FEN:$!E:70N8V]M+"!397!T96UB97(@,3DY-0`A^00!```!`"P`````%``6
M```#7SBZO/$P#$"KG2.^*8C_!#")V@2"8I5!9FA1(\P"YT</!(YO0%?3-=YK
M*"AV>+Z3Q4C@U3S$I@0XC#J?UFD2]3I.JU5O#+R4CLD4,;IK7I>%[EX[+M\,
+C/A\<0=Y^J4)`#L`
end


Done!
