import o, { assertThrows } from "@tutao/otest"
import { decapsulateKyber, encapsulateKyber, extractKyberPublicKeyFromKyberPrivateKey, generateKeyPairKyber, LibOQSExports, random } from "@tutao/crypto"
import { loadWasmModuleFallback, loadWasmModuleFromFile } from "./WebAssemblyTestUtils.js"
import fs from "node:fs"
import { execSync } from "node:child_process"

o.spec("Kyber", function () {
	// We need to generate the webassembly stuff during tests
	// since they're generated by esbuild during app build process
	// and packages tests run before the app build.
	o.before(async () => {
		const currentPath = process.cwd()

		execSync("make -f Makefile_liboqs build", {
			cwd: "../libs/webassembly",
			env: {
				...process.env,
				WASM: `${currentPath}/liboqs.wasm`,
			},
			stdio: "inherit",
		})
	})

	// We remove them after the tests since we don't need them anymore
	o.after(() => {
		fs.rmSync("./liboqs.wasm")
	})

	o("encryption roundtrip", async function () {
		const liboqs = (await loadWasmModuleFromFile("./liboqs.wasm")) as LibOQSExports

		const keyPair = generateKeyPairKyber(liboqs, random)
		o(keyPair.privateKey.raw.length).equals(3168)
		o(keyPair.publicKey.raw.length).equals(1568)

		const encapsulation = encapsulateKyber(liboqs, keyPair.publicKey, random)
		o(encapsulation.sharedSecret.length).equals(32)
		o(encapsulation.ciphertext.length).equals(1568)

		const decapsulatedSecret = decapsulateKyber(liboqs, keyPair.privateKey, encapsulation.ciphertext)

		o(encapsulation.sharedSecret).deepEquals(decapsulatedSecret)
	})

	o("liboqs fallback unavailable", async function () {
		await assertThrows(Error, async () => await loadWasmModuleFallback("../liboqs.js"))
	})

	o("extract public key", async function () {
		const liboqs = (await loadWasmModuleFromFile("./liboqs.wasm")) as LibOQSExports
		const keyPair = generateKeyPairKyber(liboqs, random)
		const extractedPublicKey = extractKyberPublicKeyFromKyberPrivateKey(keyPair.privateKey)

		o(extractedPublicKey).deepEquals(keyPair.publicKey)
	})
})
