/**
 * @license
 * Copyright 2025 Google LLC. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * =============================================================================
 */

// This file is autogenerated.


import {registerKernel} from '@tensorflow/tfjs-core/dist/base';
import '@tensorflow/tfjs-core/dist/base_side_effects';
export * from '@tensorflow/tfjs-core/dist/base';

//backend = cpu
export * from '@tensorflow/tfjs-backend-cpu/dist/base';
import {stringToHashBucketFastConfig as StringToHashBucketFast_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/StringToHashBucketFast';
registerKernel(StringToHashBucketFast_cpu);
import {reshapeConfig as Reshape_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Reshape';
registerKernel(Reshape_cpu);
import {sliceConfig as Slice_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Slice';
registerKernel(Slice_cpu);
import {castConfig as Cast_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Cast';
registerKernel(Cast_cpu);
import {gatherV2Config as GatherV2_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/GatherV2';
registerKernel(GatherV2_cpu);
import {identityConfig as Identity_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Identity';
registerKernel(Identity_cpu);
import {batchMatMulConfig as BatchMatMul_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/BatchMatMul';
registerKernel(BatchMatMul_cpu);
import {addConfig as Add_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Add';
registerKernel(Add_cpu);
import {reluConfig as Relu_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Relu';
registerKernel(Relu_cpu);
import {floorConfig as Floor_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Floor';
registerKernel(Floor_cpu);
import {realDivConfig as RealDiv_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/RealDiv';
registerKernel(RealDiv_cpu);
import {multiplyConfig as Multiply_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Multiply';
registerKernel(Multiply_cpu);
import {_fusedMatMulConfig as _FusedMatMul_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/_FusedMatMul';
registerKernel(_FusedMatMul_cpu);
import {sigmoidConfig as Sigmoid_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Sigmoid';
registerKernel(Sigmoid_cpu);
import {clipByValueConfig as ClipByValue_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/ClipByValue';
registerKernel(ClipByValue_cpu);
import {subConfig as Sub_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Sub';
registerKernel(Sub_cpu);
import {logConfig as Log_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Log';
registerKernel(Log_cpu);
import {absConfig as Abs_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Abs';
registerKernel(Abs_cpu);
import {negConfig as Neg_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Neg';
registerKernel(Neg_cpu);
import {expConfig as Exp_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Exp';
registerKernel(Exp_cpu);
import {log1pConfig as Log1p_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Log1p';
registerKernel(Log1p_cpu);
import {meanConfig as Mean_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Mean';
registerKernel(Mean_cpu);
import {onesLikeConfig as OnesLike_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/OnesLike';
registerKernel(OnesLike_cpu);
import {greaterConfig as Greater_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Greater';
registerKernel(Greater_cpu);
import {equalConfig as Equal_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Equal';
registerKernel(Equal_cpu);
import {stepConfig as Step_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Step';
registerKernel(Step_cpu);
import {squareConfig as Square_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Square';
registerKernel(Square_cpu);
import {greaterEqualConfig as GreaterEqual_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/GreaterEqual';
registerKernel(GreaterEqual_cpu);
import {lessEqualConfig as LessEqual_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/LessEqual';
registerKernel(LessEqual_cpu);
import {logicalAndConfig as LogicalAnd_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/LogicalAnd';
registerKernel(LogicalAnd_cpu);
import {zerosLikeConfig as ZerosLike_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/ZerosLike';
registerKernel(ZerosLike_cpu);
import {selectConfig as Select_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Select';
registerKernel(Select_cpu);
import {sumConfig as Sum_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Sum';
registerKernel(Sum_cpu);
import {sqrtConfig as Sqrt_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Sqrt';
registerKernel(Sqrt_cpu);