/** @type DomainConfigMap */
export const domainConfigs = {
	"mail.tutanota.com": {
		firstPartyDomain: true,
		apiUrl: "https://mail.tutanota.com",
		paymentUrl: "https://pay.tutanota.com/braintree.html",
		webauthnUrl: "https://app.tuta.com/webauthn",
		legacyWebauthnUrl: "https://mail.tutanota.com/webauthn",
		webauthnMobileUrl: "https://app.tuta.com/webauthnmobile",
		legacyWebauthnMobileUrl: "https://mail.tutanota.com/webauthnmobile",
		webauthnRpId: "tutanota.com",
		u2fAppId: "https://tutanota.com/u2f-appid.json",
		giftCardBaseUrl: "https://app.tuta.com/giftcard",
		referralBaseUrl: "https://app.tuta.com/signup",
	},
	"test.tutanota.com": {
		firstPartyDomain: true,
		apiUrl: "https://test.tutanota.com",
		paymentUrl: "https://pay.test.tutanota.com/braintree.html",
		webauthnUrl: "https://app.test.tuta.com/webauthn",
		legacyWebauthnUrl: "https://test.tutanota.com/webauthn",
		webauthnMobileUrl: "https://app.test.tuta.com/webauthnmobile",
		legacyWebauthnMobileUrl: "https://test.tutanota.com/webauthnmobile",
		webauthnRpId: "tutanota.com",
		u2fAppId: "https://test.tutanota.com/u2f-appid.json",
		giftCardBaseUrl: "https://app.test.tuta.com/giftcard",
		referralBaseUrl: "https://app.test.tuta.com/signup",
	},
	"local.tutanota.com": {
		firstPartyDomain: true,
		apiUrl: "https://local.tutanota.com:9000",
		paymentUrl: "https://local.tutanota.com:9000/client/build/braintree.html",
		webauthnUrl: "https://app.local.tuta.com:9000/client/build/webauthn",
		legacyWebauthnUrl: "https://local.tutanota.com:9000/client/build/webauthn",
		webauthnMobileUrl: "https://app.local.tuta.com:9000/client/build/webauthnmobile",
		legacyWebauthnMobileUrl: "https://local.tutanota.com:9000/client/build/webauthnmobile",
		webauthnRpId: "tutanota.com",
		u2fAppId: "https://local.tutanota.com/u2f-appid.json",
		giftCardBaseUrl: "https://app.local.tuta.com/giftcard",
		referralBaseUrl: "https://app.local.tuta.com/signup",
	},
	"app.tuta.com": {
		firstPartyDomain: true,
		apiUrl: "https://app.tuta.com",
		paymentUrl: "https://pay.tutanota.com/braintree.html",
		webauthnUrl: "https://app.tuta.com/webauthn",
		legacyWebauthnUrl: "https://mail.tutanota.com/webauthn",
		webauthnMobileUrl: "https://app.tuta.com/webauthnmobile",
		legacyWebauthnMobileUrl: "https://mail.tutanota.com/webauthnmobile",
		webauthnRpId: "tuta.com",
		u2fAppId: "https://app.tuta.com/u2f-appid.json",
		giftCardBaseUrl: "https://app.tuta.com/giftcard",
		referralBaseUrl: "https://app.tuta.com/signup",
	},
	"app.test.tuta.com": {
		firstPartyDomain: true,
		apiUrl: "https://app.test.tuta.com",
		paymentUrl: "https://pay.test.tutanota.com/braintree.html",
		webauthnUrl: "https://app.test.tuta.com/webauthn",
		legacyWebauthnUrl: "https://test.tutanota.com/webauthn",
		webauthnMobileUrl: "https://app.test.tuta.com/webauthnmobile",
		legacyWebauthnMobileUrl: "https://test.tutanota.com/webauthnmobile",
		webauthnRpId: "tuta.com",
		u2fAppId: "https://app.test.tuta.com/u2f-appid.json",
		giftCardBaseUrl: "https://app.test.tuta.com/giftcard",
		referralBaseUrl: "https://app.test.tuta.com/signup",
	},
	"app.local.tuta.com": {
		firstPartyDomain: true,
		apiUrl: "https://app.local.tuta.com:9000",
		paymentUrl: "https://app.local.tuta.com:9000/client/build/braintree.html",
		webauthnUrl: "https://app.local.tuta.com:9000/client/build/webauthn",
		legacyWebauthnUrl: "https://local.tutanota.com:9000/client/build/webauthn",
		webauthnMobileUrl: "https://app.local.tuta.com:9000/client/build/webauthnmobile",
		legacyWebauthnMobileUrl: "https://local.tutanota.com:9000/client/build/webauthnmobile",
		webauthnRpId: "tuta.com",
		u2fAppId: "https://app.local.tuta.com/u2f-appid.json",
		giftCardBaseUrl: "https://app.local.tuta.com/giftcard",
		referralBaseUrl: "https://app.local.tuta.com/signup",
	},
	localhost: {
		firstPartyDomain: true,
		apiUrl: "http://localhost:9000",
		paymentUrl: "http://localhost:9000/client/build/braintree.html",
		webauthnUrl: "http://localhost:9000/client/build/webauthn",
		legacyWebauthnUrl: "http://localhost:9000/client/build/webauthn",
		webauthnMobileUrl: "http://localhost:9000/client/build/webauthnmobile",
		legacyWebauthnMobileUrl: "http://localhost:9000/client/build/webauthnmobile",
		webauthnRpId: "localhost",
		u2fAppId: "http://localhost:9000/u2f-appid.json",
		giftCardBaseUrl: "https://localhost:9000/giftcard",
		referralBaseUrl: "https://localhost:9000/signup",
	},
	"{hostname}": {
		firstPartyDomain: false,
		apiUrl: "https://{hostname}",
		paymentUrl: "https://pay.tutanota.com/braintree.html",
		webauthnUrl: "https://{hostname}/webauthn",
		legacyWebauthnUrl: "https://{hostname}/webauthn",
		webauthnMobileUrl: "https://{hostname}/webauthnmobile",
		legacyWebauthnMobileUrl: "https://{hostname}/webauthnmobile",
		webauthnRpId: "{hostname}",
		u2fAppId: "https://{hostname}/u2f-appid.json",
		giftCardBaseUrl: "https://app.tuta.com/giftcard",
		referralBaseUrl: "https://app.tuta.com/signup",
	},
}
