name: Node CI

on:
  pull_request:
    types: [ opened, synchronize, edited ]
  push:
    branches:
      - dev-*
      - '*/dev'
env:
  emscripten_version: 3.1.59

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          submodules: 'true'
      - name: run tests
        run: |
          node ./testdates.js